// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleType
@_spi(GoogleCloudInternal) import GoogleWKT

/// Message describing the user-specified automated backup policy.
///
/// All fields in the automated backup policy are optional. Defaults for each
/// field are provided if they are not set.
public struct AutomatedBackupPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Whether automated automated backups are enabled. If not set, defaults to
  /// true.
  public var enabled: Swift.Bool? = nil

  /// The length of the time window during which a backup can be
  /// taken. If a backup does not succeed within this time window, it will be
  /// canceled and considered failed.
  ///
  /// The backup window must be at least 5 minutes long. There is no upper bound
  /// on the window. If not set, it defaults to 1 hour.
  public var backupWindow: GoogleWKT.Duration? = nil

  /// Optional. The encryption config can be specified to encrypt the
  /// backups with a customer-managed encryption key (CMEK). When this field is
  /// not specified, the backup will use the cluster's encryption config.
  public var encryptionConfig: EncryptionConfig? = nil

  /// The location where the backup will be stored. Currently, the only supported
  /// option is to store the backup in the same region as the cluster.
  ///
  /// If empty, defaults to the region of the cluster.
  public var location: Swift.String = Swift.String()

  /// Labels to apply to backups created using this configuration.
  public var labels: [Swift.String: Swift.String] = [:]

  /// The schedule for this automated backup policy.
  ///
  /// A schedule specifies times at which to start a backup. If a backup
  /// window is also provided, the backup is guaranteed to be started and
  /// completed within the start time plus the backup window. If the backup is
  /// not completed within the backup window it is marked as failed.
  ///
  /// If not set, the schedule defaults to a weekly schedule with one backup
  /// per day and a start time chosen arbitrarily.
  public var schedule: OneOf_Schedule? = nil

  /// The retention policy for automated backups.
  ///
  /// The retention policy for a backup is fixed at the time the backup is
  /// created. Changes to this field only apply to new backups taken with the
  /// policy; the retentions of existing backups remain unchanged.
  ///
  /// If no retention policy is set, a default of 14 days is used.
  public var retention: OneOf_Retention? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AutomatedBackupPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutomatedBackupPolicy().with { $0.weeklySchedule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let weeklySchedule = CodingKeys(stringValue: "weeklySchedule")
    static let timeBasedRetention = CodingKeys(stringValue: "timeBasedRetention")
    static let quantityBasedRetention = CodingKeys(stringValue: "quantityBasedRetention")
    static let enabled = CodingKeys(stringValue: "enabled")
    static let backupWindow = CodingKeys(stringValue: "backupWindow")
    static let encryptionConfig = CodingKeys(stringValue: "encryptionConfig")
    static let location = CodingKeys(stringValue: "location")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "weeklySchedule",
      "timeBasedRetention",
      "quantityBasedRetention",
      "enabled",
      "backupWindow",
      "encryptionConfig",
      "location",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.enabled = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled)
    self.backupWindow = try container.decodeIfPresent(
      GoogleWKT.Duration.self, forKey: .backupWindow)
    self.encryptionConfig = try container.decodeIfPresent(
      EncryptionConfig.self, forKey: .encryptionConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }

    var schedule: OneOf_Schedule? = nil
    let scheduleCheckAndSet = {
      if schedule != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'schedule'"))
      }
      schedule = $0
    }
    if let weeklySchedule = try container.decodeIfPresent(
      AutomatedBackupPolicy.WeeklySchedule?.self, forKey: .weeklySchedule)
    {
      try scheduleCheckAndSet(.weeklySchedule(weeklySchedule))
    }
    self.schedule = schedule

    var retention: OneOf_Retention? = nil
    let retentionCheckAndSet = {
      if retention != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'retention'"))
      }
      retention = $0
    }
    if let timeBasedRetention = try container.decodeIfPresent(
      AutomatedBackupPolicy.TimeBasedRetention?.self, forKey: .timeBasedRetention)
    {
      try retentionCheckAndSet(.timeBasedRetention(timeBasedRetention))
    }
    if let quantityBasedRetention = try container.decodeIfPresent(
      AutomatedBackupPolicy.QuantityBasedRetention?.self, forKey: .quantityBasedRetention)
    {
      try retentionCheckAndSet(.quantityBasedRetention(quantityBasedRetention))
    }
    self.retention = retention
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.enabled, forKey: .enabled)
    try container.encodeIfPresent(self.backupWindow, forKey: .backupWindow)
    try container.encodeIfPresent(self.encryptionConfig, forKey: .encryptionConfig)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.labels, forKey: .labels)

    if let choice = self.schedule {
      switch choice {
      case .weeklySchedule(let value):
        try container.encode(value, forKey: .weeklySchedule)
      }
    }

    if let choice = self.retention {
      switch choice {
      case .timeBasedRetention(let value):
        try container.encode(value, forKey: .timeBasedRetention)
      case .quantityBasedRetention(let value):
        try container.encode(value, forKey: .quantityBasedRetention)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A weekly schedule starts a backup at prescribed start times within a
  /// day, for the specified days of the week.
  ///
  /// The weekly schedule message is flexible and can be used to create many
  /// types of schedules. For example, to have a daily backup that starts at
  /// 22:00, configure the `start_times` field to have one element "22:00" and
  /// the `days_of_week` field to have all seven days of the week.
  public struct WeeklySchedule: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The times during the day to start a backup. The start times are assumed
    /// to be in UTC and to be an exact hour (e.g., 04:00:00).
    ///
    /// If no start times are provided, a single fixed start time is chosen
    /// arbitrarily.
    public var startTimes: [GoogleType.TimeOfDay] = []

    /// The days of the week to perform a backup.
    ///
    /// If this field is left empty, the default of every day of the week is
    /// used.
    public var daysOfWeek: [GoogleType.DayOfWeek] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WeeklySchedule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WeeklySchedule().with { $0.startTimes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startTimes = CodingKeys(stringValue: "startTimes")
      static let daysOfWeek = CodingKeys(stringValue: "daysOfWeek")

      static let _knownKeys: Set<Swift.String> = [
        "startTimes",
        "daysOfWeek",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([GoogleType.TimeOfDay].self, forKey: .startTimes)
      {
        self.startTimes = value
      }
      if let value = try container.decodeIfPresent([GoogleType.DayOfWeek].self, forKey: .daysOfWeek)
      {
        self.daysOfWeek = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.startTimes, forKey: .startTimes)
      try container.encode(self.daysOfWeek, forKey: .daysOfWeek)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.AutomatedBackupPolicy.WeeklySchedule"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A time based retention policy specifies that all backups within a certain
  /// time period should be retained.
  public struct TimeBasedRetention: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The retention period.
    public var retentionPeriod: GoogleWKT.Duration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TimeBasedRetention`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TimeBasedRetention().with { $0.retentionPeriod = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let retentionPeriod = CodingKeys(stringValue: "retentionPeriod")

      static let _knownKeys: Set<Swift.String> = [
        "retentionPeriod"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.retentionPeriod = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .retentionPeriod)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.retentionPeriod, forKey: .retentionPeriod)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.AutomatedBackupPolicy.TimeBasedRetention"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A quantity based policy specifies that a certain number of the most recent
  /// successful backups should be retained.
  public struct QuantityBasedRetention: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The number of backups to retain.
    public var count: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `QuantityBasedRetention`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QuantityBasedRetention().with { $0.count = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let count = CodingKeys(stringValue: "count")

      static let _knownKeys: Set<Swift.String> = [
        "count"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .count) {
        self.count = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.count, forKey: .count)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.alloydb.v1.AutomatedBackupPolicy.QuantityBasedRetention"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The schedule for this automated backup policy.
  ///
  /// A schedule specifies times at which to start a backup. If a backup
  /// window is also provided, the backup is guaranteed to be started and
  /// completed within the start time plus the backup window. If the backup is
  /// not completed within the backup window it is marked as failed.
  ///
  /// If not set, the schedule defaults to a weekly schedule with one backup
  /// per day and a start time chosen arbitrarily.
  public enum OneOf_Schedule: Codable, Equatable, Sendable {
    /// Weekly schedule for the Backup.
    indirect case weeklySchedule(AutomatedBackupPolicy.WeeklySchedule?)
  }

  /// The retention policy for automated backups.
  ///
  /// The retention policy for a backup is fixed at the time the backup is
  /// created. Changes to this field only apply to new backups taken with the
  /// policy; the retentions of existing backups remain unchanged.
  ///
  /// If no retention policy is set, a default of 14 days is used.
  public enum OneOf_Retention: Codable, Equatable, Sendable {
    /// Time-based Backup retention policy.
    indirect case timeBasedRetention(AutomatedBackupPolicy.TimeBasedRetention?)
    /// Quantity-based Backup retention policy to retain recent backups.
    indirect case quantityBasedRetention(AutomatedBackupPolicy.QuantityBasedRetention?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.AutomatedBackupPolicy"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
