// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message for metadata that is specific to BatchCreateInstances API.
/// NEXT_ID: 3
public struct BatchCreateInstancesMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The instances being created in the API call. Each string in this list
  /// is the server defined resource path for target instances in the request
  /// and for the format of each string, see the comment on the Instance.name
  /// field.
  public var instanceTargets: [Swift.String] = []

  /// A map representing state of the instances involved in the
  /// BatchCreateInstances operation during the operation execution.
  /// The instance state will be in STATE_UNSPECIFIED state if the instance has
  /// not yet been picked up for processing.
  /// The key of the map is the name of the instance resource.
  /// For the format, see the comment on the Instance.name field.
  public var instanceStatuses: [Swift.String: BatchCreateInstanceStatus] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchCreateInstancesMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchCreateInstancesMetadata().with { $0.instanceTargets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let instanceTargets = CodingKeys(stringValue: "instanceTargets")
    static let instanceStatuses = CodingKeys(stringValue: "instanceStatuses")

    static let _knownKeys: Set<Swift.String> = [
      "instanceTargets",
      "instanceStatuses",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .instanceTargets) {
      self.instanceTargets = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: BatchCreateInstanceStatus].self, forKey: .instanceStatuses)
    {
      self.instanceStatuses = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.instanceTargets, forKey: .instanceTargets)
    try container.encode(self.instanceStatuses, forKey: .instanceStatuses)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.BatchCreateInstancesMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
