// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Message for current status of an instance in the BatchCreateInstances
/// operation.
/// For example, lets say a BatchCreateInstances workflow has 4 instances,
/// Instance1 through Instance4. Lets also assume that 2 instances succeeded
/// but the third failed to create and the 4th was never picked up for creation
/// because of failure of the previous one. Then, resulting states would look
/// something like:
///   1. Instance1 = ROLLED_BACK
///   2. Instance2 = ROLLED_BACK
///   3. Instance3 = FAILED
///   4. Instance4 = FAILED
///
/// However, while the operation is running, the instance might be in other
/// states including PENDING_CREATE, ACTIVE, DELETING and CREATING. The states
/// / do not get further updated once the operation is done.
public struct BatchCreateInstanceStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The current state of an instance involved in the batch create operation.
  /// Once the operation is complete, the final state of the instances in the
  /// LRO can be one of:
  ///   1. ACTIVE, indicating that instances were created successfully
  ///   2. FAILED, indicating that a particular instance failed creation
  ///   3. ROLLED_BACK indicating that although the instance was created
  ///      successfully, it had to be rolled back and deleted due to failure in
  ///      other steps of the workflow.
  public var state: BatchCreateInstanceStatus.State = BatchCreateInstanceStatus.State()

  /// DEPRECATED - Use the error field instead.
  /// Error, if any error occurred and is available, during instance creation.
  public var errorMsg: Swift.String = Swift.String()

  /// The RPC status of the instance creation operation. This field will be
  /// present if an error happened during the instance creation.
  public var error: GoogleRpc.Status? = nil

  public var type: Instance.InstanceType = Instance.InstanceType()

  /// Initialize a new instance of `BatchCreateInstanceStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchCreateInstanceStatus().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State contains all valid instance states for the BatchCreateInstances
  /// operation. This is mainly used for status reporting through the LRO
  /// metadata.
  public enum State: Codable, Equatable, Sendable {
    /// The state of the instance is unknown.
    case unspecified
    /// Instance is pending creation and has not yet been picked up for
    /// processing in the backend.
    case pendingCreate
    /// The instance is active and running.
    case ready
    /// The instance is being created.
    case creating
    /// The instance is being deleted.
    case deleting
    /// The creation of the instance failed or a fatal error occurred during
    /// an operation on the instance or a batch of instances.
    case failed
    /// The instance was created successfully, but was rolled back and deleted
    /// due to some other failure during BatchCreateInstances operation.
    case rolledBack
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pendingCreate: return 1
      case .ready: return 2
      case .creating: return 3
      case .deleting: return 4
      case .failed: return 5
      case .rolledBack: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .pendingCreate: return "PENDING_CREATE"
      case .ready: return "READY"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .failed: return "FAILED"
      case .rolledBack: return "ROLLED_BACK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING_CREATE": self = .pendingCreate
      case "READY": self = .ready
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "FAILED": self = .failed
      case "ROLLED_BACK": self = .rolledBack
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pendingCreate
      case 2: self = .ready
      case 3: self = .creating
      case 4: self = .deleting
      case 5: self = .failed
      case 6: self = .rolledBack
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pendingCreate: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .creating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .failed: return try container.encode(5)
      case .rolledBack: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.BatchCreateInstanceStatus"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
