// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message for metadata that is specific to BatchCreateInstances API.
/// NEXT_ID: 3
public struct BatchCreateInstancesMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The instances being created in the API call. Each string in this list
  /// is the server defined resource path for target instances in the request
  /// and for the format of each string, see the comment on the Instance.name
  /// field.
  public var instanceTargets: [Swift.String] = []

  /// A map representing state of the instances involved in the
  /// BatchCreateInstances operation during the operation execution.
  /// The instance state will be in STATE_UNSPECIFIED state if the instance has
  /// not yet been picked up for processing.
  /// The key of the map is the name of the instance resource.
  /// For the format, see the comment on the Instance.name field.
  public var instanceStatuses: [Swift.String: BatchCreateInstanceStatus] = [:]

  /// Initialize a new instance of `BatchCreateInstancesMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchCreateInstancesMetadata().with { $0.instanceTargets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.BatchCreateInstancesMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
