// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The source CloudSQL backup resource.
public struct CloudSQLBackupRunSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The project ID of the source CloudSQL instance. This should be the same as
  /// the AlloyDB cluster's project.
  public var project: Swift.String = Swift.String()

  /// Required. The CloudSQL instance ID.
  public var instanceId: Swift.String = Swift.String()

  /// Required. The CloudSQL backup run ID.
  public var backupRunId: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `CloudSQLBackupRunSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudSQLBackupRunSource().with { $0.project = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.CloudSQLBackupRunSource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
