// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A cluster is a collection of regional AlloyDB resources. It can include a
/// primary instance and one or more read pool instances.
/// All cluster resources share a storage layer, which scales as needed.
public struct Cluster: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the cluster resource with the format:
  ///  * projects/{project}/locations/{region}/clusters/{cluster_id}
  /// where the cluster ID segment should satisfy the regex expression
  /// `[a-z0-9-]+`. For more details see https://google.aip.dev/122.
  /// The prefix of the cluster resource name is the name of the parent resource:
  ///  * projects/{project}/locations/{region}
  public var name: Swift.String = Swift.String()

  /// User-settable and human-readable display name for the Cluster.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The system-generated UID of the resource. The UID is assigned
  /// when the resource is created, and it is retained until it is deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. Create time stamp
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Update time stamp
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. Delete time stamp
  public var deleteTime: GoogleWKT.Timestamp? = nil

  /// Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The current serving state of the cluster.
  public var state: Cluster.State = Cluster.State()

  /// Output only. The type of the cluster. This is an output-only field and it's
  /// populated at the Cluster creation time or the Cluster promotion
  /// time. The cluster type is determined by which RPC was used to create
  /// the cluster (i.e. `CreateCluster` vs. `CreateSecondaryCluster`
  public var clusterType: Cluster.ClusterType = Cluster.ClusterType()

  /// Optional. The database engine major version. This is an optional field and
  /// it is populated at the Cluster creation time. If a database version is not
  /// supplied at cluster creation time, then a default database version will
  /// be used.
  public var databaseVersion: DatabaseVersion = DatabaseVersion()

  public var networkConfig: Cluster.NetworkConfig? = nil

  /// Required. The resource link for the VPC network in which cluster resources
  /// are created and from which they are accessible via Private IP. The network
  /// must belong to the same project as the cluster. It is specified in the
  /// form: `projects/{project}/global/networks/{network_id}`. This is required
  /// to create a cluster. Deprecated, use network_config.network instead.
  @available(*, deprecated)
  public var network: Swift.String = Swift.String()

  /// For Resource freshness validation (https://google.aip.dev/154)
  public var etag: Swift.String = Swift.String()

  /// Annotations to allow client tools to store small amount of arbitrary data.
  /// This is distinct from labels.
  /// https://google.aip.dev/128
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. Reconciling (https://google.aip.dev/128#reconciliation).
  /// Set to true if the current state of Cluster does not match the user's
  /// intended state, and the service is actively updating the resource to
  /// reconcile them. This can happen due to user-triggered updates or
  /// system actions like failover or maintenance.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Input only. Initial user to setup during cluster creation.
  /// If used in `RestoreCluster` this is ignored.
  public var initialUser: UserPassword? = nil

  /// The automated backup policy for this cluster.
  ///
  /// If no policy is provided then the default policy will be used. If backups
  /// are supported for the cluster, the default policy takes one backup a day,
  /// has a backup window of 1 hour, and retains backups for 14 days.
  /// For more information on the defaults, consult the
  /// documentation for the message type.
  public var automatedBackupPolicy: AutomatedBackupPolicy? = nil

  /// SSL configuration for this AlloyDB cluster.
  @available(*, deprecated)
  public var sslConfig: SslConfig? = nil

  /// Optional. The encryption config can be specified to encrypt the data disks
  /// and other persistent data resources of a cluster with a
  /// customer-managed encryption key (CMEK). When this field is not
  /// specified, the cluster will then use default encryption scheme to
  /// protect the user data.
  public var encryptionConfig: EncryptionConfig? = nil

  /// Output only. The encryption information for the cluster.
  public var encryptionInfo: EncryptionInfo? = nil

  /// Optional. Continuous backup configuration for this cluster.
  public var continuousBackupConfig: ContinuousBackupConfig? = nil

  /// Output only. Continuous backup properties for this cluster.
  public var continuousBackupInfo: ContinuousBackupInfo? = nil

  /// Cross Region replication config specific to SECONDARY cluster.
  public var secondaryConfig: Cluster.SecondaryConfig? = nil

  /// Output only. Cross Region replication config specific to PRIMARY cluster.
  public var primaryConfig: Cluster.PrimaryConfig? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Optional. The configuration for Private Service Connect (PSC) for the
  /// cluster.
  public var pscConfig: Cluster.PscConfig? = nil

  /// Optional. The maintenance update policy determines when to allow or deny
  /// updates.
  public var maintenanceUpdatePolicy: MaintenanceUpdatePolicy? = nil

  /// Output only. The maintenance schedule for the cluster, generated for a
  /// specific rollout if a maintenance window is set.
  public var maintenanceSchedule: MaintenanceSchedule? = nil

  /// Optional. Subscription type of the cluster.
  public var subscriptionType: SubscriptionType = SubscriptionType()

  /// Output only. Metadata for free trial clusters
  public var trialMetadata: Cluster.TrialMetadata? = nil

  /// Optional. Input only. Immutable. Tag keys/values directly bound to this
  /// resource. For example:
  /// ```
  /// "123/environment": "production",
  /// "123/costCenter": "marketing"
  /// ```
  public var tags: [Swift.String: Swift.String] = [:]

  /// Optional. Configuration for Dataplex integration.
  public var dataplexConfig: Cluster.DataplexConfig? = nil

  /// In case of an imported cluster, this field contains information about the
  /// source this cluster was imported from.
  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Cluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Cluster().with { $0.backupSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let backupSource = CodingKeys(stringValue: "backupSource")
    static let migrationSource = CodingKeys(stringValue: "migrationSource")
    static let cloudsqlBackupRunSource = CodingKeys(stringValue: "cloudsqlBackupRunSource")
    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let state = CodingKeys(stringValue: "state")
    static let clusterType = CodingKeys(stringValue: "clusterType")
    static let databaseVersion = CodingKeys(stringValue: "databaseVersion")
    static let networkConfig = CodingKeys(stringValue: "networkConfig")
    static let network = CodingKeys(stringValue: "network")
    static let etag = CodingKeys(stringValue: "etag")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let reconciling = CodingKeys(stringValue: "reconciling")
    static let initialUser = CodingKeys(stringValue: "initialUser")
    static let automatedBackupPolicy = CodingKeys(stringValue: "automatedBackupPolicy")
    static let sslConfig = CodingKeys(stringValue: "sslConfig")
    static let encryptionConfig = CodingKeys(stringValue: "encryptionConfig")
    static let encryptionInfo = CodingKeys(stringValue: "encryptionInfo")
    static let continuousBackupConfig = CodingKeys(stringValue: "continuousBackupConfig")
    static let continuousBackupInfo = CodingKeys(stringValue: "continuousBackupInfo")
    static let secondaryConfig = CodingKeys(stringValue: "secondaryConfig")
    static let primaryConfig = CodingKeys(stringValue: "primaryConfig")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let pscConfig = CodingKeys(stringValue: "pscConfig")
    static let maintenanceUpdatePolicy = CodingKeys(stringValue: "maintenanceUpdatePolicy")
    static let maintenanceSchedule = CodingKeys(stringValue: "maintenanceSchedule")
    static let subscriptionType = CodingKeys(stringValue: "subscriptionType")
    static let trialMetadata = CodingKeys(stringValue: "trialMetadata")
    static let tags = CodingKeys(stringValue: "tags")
    static let dataplexConfig = CodingKeys(stringValue: "dataplexConfig")

    static let _knownKeys: Set<Swift.String> = [
      "backupSource",
      "migrationSource",
      "cloudsqlBackupRunSource",
      "name",
      "displayName",
      "uid",
      "createTime",
      "updateTime",
      "deleteTime",
      "labels",
      "state",
      "clusterType",
      "databaseVersion",
      "networkConfig",
      "network",
      "etag",
      "annotations",
      "reconciling",
      "initialUser",
      "automatedBackupPolicy",
      "sslConfig",
      "encryptionConfig",
      "encryptionInfo",
      "continuousBackupConfig",
      "continuousBackupInfo",
      "secondaryConfig",
      "primaryConfig",
      "satisfiesPzs",
      "pscConfig",
      "maintenanceUpdatePolicy",
      "maintenanceSchedule",
      "subscriptionType",
      "trialMetadata",
      "tags",
      "dataplexConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Cluster.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Cluster.ClusterType.self, forKey: .clusterType) {
      self.clusterType = value
    }
    if let value = try container.decodeIfPresent(DatabaseVersion.self, forKey: .databaseVersion) {
      self.databaseVersion = value
    }
    self.networkConfig = try container.decodeIfPresent(
      Cluster.NetworkConfig.self, forKey: .networkConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reconciling) {
      self.reconciling = value
    }
    self.initialUser = try container.decodeIfPresent(UserPassword.self, forKey: .initialUser)
    self.automatedBackupPolicy = try container.decodeIfPresent(
      AutomatedBackupPolicy.self, forKey: .automatedBackupPolicy)
    self.sslConfig = try container.decodeIfPresent(SslConfig.self, forKey: .sslConfig)
    self.encryptionConfig = try container.decodeIfPresent(
      EncryptionConfig.self, forKey: .encryptionConfig)
    self.encryptionInfo = try container.decodeIfPresent(
      EncryptionInfo.self, forKey: .encryptionInfo)
    self.continuousBackupConfig = try container.decodeIfPresent(
      ContinuousBackupConfig.self, forKey: .continuousBackupConfig)
    self.continuousBackupInfo = try container.decodeIfPresent(
      ContinuousBackupInfo.self, forKey: .continuousBackupInfo)
    self.secondaryConfig = try container.decodeIfPresent(
      Cluster.SecondaryConfig.self, forKey: .secondaryConfig)
    self.primaryConfig = try container.decodeIfPresent(
      Cluster.PrimaryConfig.self, forKey: .primaryConfig)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs) {
      self.satisfiesPzs = value
    }
    self.pscConfig = try container.decodeIfPresent(Cluster.PscConfig.self, forKey: .pscConfig)
    self.maintenanceUpdatePolicy = try container.decodeIfPresent(
      MaintenanceUpdatePolicy.self, forKey: .maintenanceUpdatePolicy)
    self.maintenanceSchedule = try container.decodeIfPresent(
      MaintenanceSchedule.self, forKey: .maintenanceSchedule)
    if let value = try container.decodeIfPresent(SubscriptionType.self, forKey: .subscriptionType) {
      self.subscriptionType = value
    }
    self.trialMetadata = try container.decodeIfPresent(
      Cluster.TrialMetadata.self, forKey: .trialMetadata)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    self.dataplexConfig = try container.decodeIfPresent(
      Cluster.DataplexConfig.self, forKey: .dataplexConfig)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let backupSource = try container.decodeIfPresent(BackupSource?.self, forKey: .backupSource) {
      try sourceCheckAndSet(.backupSource(backupSource))
    }
    if let migrationSource = try container.decodeIfPresent(
      MigrationSource?.self, forKey: .migrationSource)
    {
      try sourceCheckAndSet(.migrationSource(migrationSource))
    }
    if let cloudsqlBackupRunSource = try container.decodeIfPresent(
      CloudSQLBackupRunSource?.self, forKey: .cloudsqlBackupRunSource)
    {
      try sourceCheckAndSet(.cloudsqlBackupRunSource(cloudsqlBackupRunSource))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.clusterType, forKey: .clusterType)
    try container.encode(self.databaseVersion, forKey: .databaseVersion)
    try container.encodeIfPresent(self.networkConfig, forKey: .networkConfig)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encodeIfPresent(self.initialUser, forKey: .initialUser)
    try container.encodeIfPresent(self.automatedBackupPolicy, forKey: .automatedBackupPolicy)
    try container.encodeIfPresent(self.sslConfig, forKey: .sslConfig)
    try container.encodeIfPresent(self.encryptionConfig, forKey: .encryptionConfig)
    try container.encodeIfPresent(self.encryptionInfo, forKey: .encryptionInfo)
    try container.encodeIfPresent(self.continuousBackupConfig, forKey: .continuousBackupConfig)
    try container.encodeIfPresent(self.continuousBackupInfo, forKey: .continuousBackupInfo)
    try container.encodeIfPresent(self.secondaryConfig, forKey: .secondaryConfig)
    try container.encodeIfPresent(self.primaryConfig, forKey: .primaryConfig)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encodeIfPresent(self.pscConfig, forKey: .pscConfig)
    try container.encodeIfPresent(self.maintenanceUpdatePolicy, forKey: .maintenanceUpdatePolicy)
    try container.encodeIfPresent(self.maintenanceSchedule, forKey: .maintenanceSchedule)
    try container.encode(self.subscriptionType, forKey: .subscriptionType)
    try container.encodeIfPresent(self.trialMetadata, forKey: .trialMetadata)
    try container.encode(self.tags, forKey: .tags)
    try container.encodeIfPresent(self.dataplexConfig, forKey: .dataplexConfig)

    if let choice = self.source {
      switch choice {
      case .backupSource(let value):
        try container.encode(value, forKey: .backupSource)
      case .migrationSource(let value):
        try container.encode(value, forKey: .migrationSource)
      case .cloudsqlBackupRunSource(let value):
        try container.encode(value, forKey: .cloudsqlBackupRunSource)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Metadata related to network configuration.
  public struct NetworkConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The resource link for the VPC network in which cluster
    /// resources are created and from which they are accessible via Private IP.
    /// The network must belong to the same project as the cluster. It is
    /// specified in the form:
    /// `projects/{project_number}/global/networks/{network_id}`. This is
    /// required to create a cluster.
    public var network: Swift.String = Swift.String()

    /// Optional. Name of the allocated IP range for the private IP AlloyDB
    /// cluster, for example: "google-managed-services-default". If set, the
    /// instance IPs for this cluster will be created in the allocated range. The
    /// range name must comply with RFC 1035. Specifically, the name must be 1-63
    /// characters long and match the regular expression
    /// `[a-z]([-a-z0-9]*[a-z0-9])?`.
    /// Field name is intended to be consistent with Cloud SQL.
    public var allocatedIpRange: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NetworkConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NetworkConfig().with { $0.network = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let network = CodingKeys(stringValue: "network")
      static let allocatedIpRange = CodingKeys(stringValue: "allocatedIpRange")

      static let _knownKeys: Set<Swift.String> = [
        "network",
        "allocatedIpRange",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
        self.network = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .allocatedIpRange) {
        self.allocatedIpRange = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.network, forKey: .network)
      try container.encode(self.allocatedIpRange, forKey: .allocatedIpRange)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Cluster.NetworkConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration information for the secondary cluster. This should be set
  /// if and only if the cluster is of type SECONDARY.
  public struct SecondaryConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the primary cluster name with the format:
    /// * projects/{project}/locations/{region}/clusters/{cluster_id}
    public var primaryClusterName: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SecondaryConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SecondaryConfig().with { $0.primaryClusterName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let primaryClusterName = CodingKeys(stringValue: "primaryClusterName")

      static let _knownKeys: Set<Swift.String> = [
        "primaryClusterName"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .primaryClusterName) {
        self.primaryClusterName = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.primaryClusterName, forKey: .primaryClusterName)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Cluster.SecondaryConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for the primary cluster. It has the list of clusters that are
  /// replicating from this cluster. This should be set if and only if the
  /// cluster is of type PRIMARY.
  public struct PrimaryConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Names of the clusters that are replicating from this
    /// cluster.
    public var secondaryClusterNames: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PrimaryConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PrimaryConfig().with { $0.secondaryClusterNames = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let secondaryClusterNames = CodingKeys(stringValue: "secondaryClusterNames")

      static let _knownKeys: Set<Swift.String> = [
        "secondaryClusterNames"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .secondaryClusterNames)
      {
        self.secondaryClusterNames = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.secondaryClusterNames, forKey: .secondaryClusterNames)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Cluster.PrimaryConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// PscConfig contains PSC related configuration at a cluster level.
  public struct PscConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Create an instance that allows connections from Private Service
    /// Connect endpoints to the instance.
    public var pscEnabled: Swift.Bool = Swift.Bool()

    /// Output only. The project number that needs to be allowlisted on the
    /// network attachment to enable outbound connectivity.
    public var serviceOwnedProjectNumber: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PscConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscConfig().with { $0.pscEnabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let pscEnabled = CodingKeys(stringValue: "pscEnabled")
      static let serviceOwnedProjectNumber = CodingKeys(stringValue: "serviceOwnedProjectNumber")

      static let _knownKeys: Set<Swift.String> = [
        "pscEnabled",
        "serviceOwnedProjectNumber",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .pscEnabled) {
        self.pscEnabled = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .serviceOwnedProjectNumber)
      {
        self.serviceOwnedProjectNumber = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.pscEnabled, forKey: .pscEnabled)
      try container.encode(self.serviceOwnedProjectNumber, forKey: .serviceOwnedProjectNumber)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Cluster.PscConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Contains information and all metadata related to TRIAL clusters.
  public struct TrialMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// start time of the trial cluster.
    public var startTime: GoogleWKT.Timestamp? = nil

    /// End time of the trial cluster.
    public var endTime: GoogleWKT.Timestamp? = nil

    /// Upgrade time of trial cluster to Standard cluster.
    public var upgradeTime: GoogleWKT.Timestamp? = nil

    /// grace end time of the cluster.
    public var graceEndTime: GoogleWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TrialMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TrialMetadata().with { $0.startTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startTime = CodingKeys(stringValue: "startTime")
      static let endTime = CodingKeys(stringValue: "endTime")
      static let upgradeTime = CodingKeys(stringValue: "upgradeTime")
      static let graceEndTime = CodingKeys(stringValue: "graceEndTime")

      static let _knownKeys: Set<Swift.String> = [
        "startTime",
        "endTime",
        "upgradeTime",
        "graceEndTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
      self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
      self.upgradeTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .upgradeTime)
      self.graceEndTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .graceEndTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.startTime, forKey: .startTime)
      try container.encodeIfPresent(self.endTime, forKey: .endTime)
      try container.encodeIfPresent(self.upgradeTime, forKey: .upgradeTime)
      try container.encodeIfPresent(self.graceEndTime, forKey: .graceEndTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Cluster.TrialMetadata"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for Dataplex integration.
  public struct DataplexConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Dataplex is enabled by default for resources such as clusters and
    /// instances. This flag controls the integration of AlloyDB PG
    /// resources (like databases, schemas, and tables) with Dataplex."
    public var enabled: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DataplexConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DataplexConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enabled = CodingKeys(stringValue: "enabled")

      static let _knownKeys: Set<Swift.String> = [
        "enabled"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled) {
        self.enabled = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enabled, forKey: .enabled)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Cluster.DataplexConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Cluster State
  public enum State: Codable, Equatable, Sendable {
    /// The state of the cluster is unknown.
    case unspecified
    /// The cluster is active and running.
    case ready
    /// This is unused. Even when all instances in the cluster are stopped, the
    /// cluster remains in READY state.
    case stopped
    /// The cluster is empty and has no associated resources.
    /// All instances, associated storage and backups have been deleted.
    case empty
    /// The cluster is being created.
    case creating
    /// The cluster is being deleted.
    case deleting
    /// The creation of the cluster failed.
    case failed
    /// The cluster is bootstrapping with data from some other source.
    /// Direct mutations to the cluster (e.g. adding read pool) are not allowed.
    case bootstrapping
    /// The cluster is under maintenance. AlloyDB regularly performs maintenance
    /// and upgrades on customer clusters. Updates on the cluster are
    /// not allowed while the cluster is in this state.
    case maintenance
    /// The cluster is being promoted.
    case promoting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ready: return 1
      case .stopped: return 2
      case .empty: return 3
      case .creating: return 4
      case .deleting: return 5
      case .failed: return 6
      case .bootstrapping: return 7
      case .maintenance: return 8
      case .promoting: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .ready: return "READY"
      case .stopped: return "STOPPED"
      case .empty: return "EMPTY"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .failed: return "FAILED"
      case .bootstrapping: return "BOOTSTRAPPING"
      case .maintenance: return "MAINTENANCE"
      case .promoting: return "PROMOTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "READY": self = .ready
      case "STOPPED": self = .stopped
      case "EMPTY": self = .empty
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "FAILED": self = .failed
      case "BOOTSTRAPPING": self = .bootstrapping
      case "MAINTENANCE": self = .maintenance
      case "PROMOTING": self = .promoting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ready
      case 2: self = .stopped
      case 3: self = .empty
      case 4: self = .creating
      case 5: self = .deleting
      case 6: self = .failed
      case 7: self = .bootstrapping
      case 8: self = .maintenance
      case 9: self = .promoting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .ready: return try container.encode("READY")
      case .stopped: return try container.encode("STOPPED")
      case .empty: return try container.encode("EMPTY")
      case .creating: return try container.encode("CREATING")
      case .deleting: return try container.encode("DELETING")
      case .failed: return try container.encode("FAILED")
      case .bootstrapping: return try container.encode("BOOTSTRAPPING")
      case .maintenance: return try container.encode("MAINTENANCE")
      case .promoting: return try container.encode("PROMOTING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of Cluster
  public enum ClusterType: Codable, Equatable, Sendable {
    /// The type of the cluster is unknown.
    case unspecified
    /// Primary cluster that support read and write operations.
    case primary
    /// Secondary cluster that is replicating from another region.
    /// This only supports read.
    case secondary
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .primary: return 1
      case .secondary: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLUSTER_TYPE_UNSPECIFIED"
      case .primary: return "PRIMARY"
      case .secondary: return "SECONDARY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ClusterType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLUSTER_TYPE_UNSPECIFIED": self = .unspecified
      case "PRIMARY": self = .primary
      case "SECONDARY": self = .secondary
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ClusterType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .primary
      case 2: self = .secondary
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CLUSTER_TYPE_UNSPECIFIED")
      case .primary: return try container.encode("PRIMARY")
      case .secondary: return try container.encode("SECONDARY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// In case of an imported cluster, this field contains information about the
  /// source this cluster was imported from.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Output only. Cluster created from backup.
    indirect case backupSource(BackupSource?)
    /// Output only. Cluster created via DMS migration.
    indirect case migrationSource(MigrationSource?)
    /// Output only. Cluster created from CloudSQL snapshot.
    indirect case cloudsqlBackupRunSource(CloudSQLBackupRunSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.Cluster"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
