// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ConnectionInfo singleton resource.
/// https://google.aip.dev/156
public struct ConnectionInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the ConnectionInfo singleton resource, e.g.:
  /// projects/{project}/locations/{location}/clusters/*/instances/*/connectionInfo
  /// This field currently has no semantic meaning.
  public var name: Swift.String = Swift.String()

  /// Output only. The private network IP address for the Instance. This is the
  /// default IP for the instance and is always created (even if enable_public_ip
  /// is set). This is the connection endpoint for an end-user application.
  public var ipAddress: Swift.String = Swift.String()

  /// Output only. The public IP addresses for the Instance. This is available
  /// ONLY when enable_public_ip is set. This is the connection endpoint for an
  /// end-user application.
  public var publicIpAddress: Swift.String = Swift.String()

  /// Output only. The unique ID of the Instance.
  public var instanceUid: Swift.String = Swift.String()

  /// Initialize a new instance of `ConnectionInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConnectionInfo().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.ConnectionInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
