// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleType

/// ContinuousBackupInfo describes the continuous backup properties of a
/// cluster.
public struct ContinuousBackupInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The encryption information for the WALs and backups required
  /// for ContinuousBackup.
  public var encryptionInfo: EncryptionInfo? = nil

  /// Output only. When ContinuousBackup was most recently enabled. Set to null
  /// if ContinuousBackup is not enabled.
  public var enabledTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Days of the week on which a continuous backup is taken.
  public var schedule: [GoogleType.DayOfWeek] = []

  /// Output only. The earliest restorable time that can be restored to. If
  /// continuous backups and recovery was recently enabled, the earliest
  /// restorable time is the creation time of the earliest eligible backup within
  /// this cluster's continuous backup recovery window. After a cluster has had
  /// continuous backups enabled for the duration of its recovery window, the
  /// earliest restorable time becomes "now minus the recovery window". For
  /// example, assuming a point in time recovery is attempted at 04/16/2025
  /// 3:23:00PM with a 14d recovery window, the earliest restorable time would be
  /// 04/02/2025 3:23:00PM. This field is only visible if the
  /// CLUSTER_VIEW_CONTINUOUS_BACKUP cluster view is provided.
  public var earliestRestorableTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `ContinuousBackupInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContinuousBackupInfo().with { $0.encryptionInfo = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.ContinuousBackupInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
