// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The supported database engine versions.
public enum DatabaseVersion: Codable, Equatable, Sendable {
  /// This is an unknown database version.
  case unspecified
  /// DEPRECATED - The database version is Postgres 13.
  @available(*, deprecated)
  case postgres13
  /// The database version is Postgres 14.
  case postgres14
  /// The database version is Postgres 15.
  case postgres15
  /// The database version is Postgres 16.
  case postgres16
  /// The database version is Postgres 17.
  case postgres17
  /// The database version is Postgres 18.
  case postgres18
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .postgres13: return 1
    case .postgres14: return 2
    case .postgres15: return 3
    case .postgres16: return 4
    case .postgres17: return 5
    case .postgres18: return 6
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "DATABASE_VERSION_UNSPECIFIED"
    case .postgres13: return "POSTGRES_13"
    case .postgres14: return "POSTGRES_14"
    case .postgres15: return "POSTGRES_15"
    case .postgres16: return "POSTGRES_16"
    case .postgres17: return "POSTGRES_17"
    case .postgres18: return "POSTGRES_18"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DatabaseVersion/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "DATABASE_VERSION_UNSPECIFIED": self = .unspecified
    case "POSTGRES_13": self = .postgres13
    case "POSTGRES_14": self = .postgres14
    case "POSTGRES_15": self = .postgres15
    case "POSTGRES_16": self = .postgres16
    case "POSTGRES_17": self = .postgres17
    case "POSTGRES_18": self = .postgres18
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DatabaseVersion/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .postgres13
    case 2: self = .postgres14
    case 3: self = .postgres15
    case 4: self = .postgres16
    case 5: self = .postgres17
    case 6: self = .postgres18
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .postgres13: return try container.encode(1)
    case .postgres14: return try container.encode(2)
    case .postgres15: return try container.encode(3)
    case .postgres16: return try container.encode(4)
    case .postgres17: return try container.encode(5)
    case .postgres18: return try container.encode(6)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
