// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Any additional metadata information regarding the execution of the SQL
public struct ExecuteSqlMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Message related to SQL execution. Marked as core content since it
  /// can potentially contain details related to the query or result set. This
  /// field can be used to convey messages such as "when the SQL result set
  /// exceeds the acceptable response size limits."
  public var message: Swift.String = Swift.String()

  /// Set to true if SQL returned a result set larger than the acceptable
  /// response size limits and the result was truncated.
  public var partialResult: Swift.Bool = Swift.Bool()

  /// The time duration taken to execute the sql statement.
  public var sqlStatementExecutionDuration: GoogleCloudWkt.Duration? = nil

  /// Status of SQL execution.
  public var status: ExecuteSqlMetadata.Status = ExecuteSqlMetadata.Status()

  /// Initialize a new instance of `ExecuteSqlMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExecuteSqlMetadata().with { $0.message = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Status contains all valid Status a SQL execution can end up in.
  public enum Status: Codable, Equatable, Sendable {
    /// The status is unknown.
    case unspecified
    /// No error during SQL execution i.e. All SQL statements ran to completion.
    /// The "message" will be empty.
    case ok
    /// Same as OK, except indicates that only partial results were
    /// returned. The "message" field will contain details on why results were
    /// truncated.
    case partial
    /// Error during SQL execution. Atleast 1 SQL statement execution resulted in
    /// a error. Side effects of other statements are rolled back.  The "message"
    /// field will contain human readable error given by Postgres of the first
    /// bad SQL statement. SQL execution errors don't constitute API errors as
    /// defined in https://google.aip.dev/193 but will be returned as part of
    /// this message.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ok: return 1
      case .partial: return 2
      case .error: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .ok: return "OK"
      case .partial: return "PARTIAL"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Status/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "OK": self = .ok
      case "PARTIAL": self = .partial
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Status/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ok
      case 2: self = .partial
      case 3: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ok: return try container.encode(1)
      case .partial: return try container.encode(2)
      case .error: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.ExecuteSqlMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
