// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for ExecuteSql rpc.
public struct ExecuteSqlRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The instance where the SQL will be executed. For the required
  /// format, see the comment on the Instance.name field.
  public var instance: Swift.String = Swift.String()

  /// Required. Name of the database where the query will be executed.
  /// Note - Value provided should be the same as expected from `SELECT
  /// current_database();` and NOT as a resource reference.
  public var database: Swift.String = Swift.String()

  /// Required. Database user to be used for executing the SQL.
  /// Note - Value provided should be the same as expected from
  /// `SELECT current_user;` and NOT as a resource reference.
  public var user: Swift.String = Swift.String()

  /// Required. SQL statement to execute on database. Any valid statement is
  /// permitted, including DDL, DML, DQL statements.
  public var sqlStatement: Swift.String = Swift.String()

  /// Optional. If set, validates the sql statement by performing
  /// syntax and semantic validation and doesn't execute the query.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Oneof field to support other credential mechanisms in future like
  /// SecretManager etc.
  public var userCredential: OneOf_UserCredential? = nil

  /// Initialize a new instance of `ExecuteSqlRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExecuteSqlRequest().with { $0.password = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case password = "password"
    case instance = "instance"
    case database = "database"
    case user = "user"
    case sqlStatement = "sqlStatement"
    case validateOnly = "validateOnly"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.instance = try container.decode(Swift.String.self, forKey: .instance)
    self.database = try container.decode(Swift.String.self, forKey: .database)
    self.user = try container.decode(Swift.String.self, forKey: .user)
    self.sqlStatement = try container.decode(Swift.String.self, forKey: .sqlStatement)
    self.validateOnly = try container.decode(Swift.Bool.self, forKey: .validateOnly)

    var userCredential: OneOf_UserCredential? = nil
    let userCredentialCheckAndSet = {
      if userCredential != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'userCredential'"))
      }
      userCredential = $0
    }
    if let password = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
      try userCredentialCheckAndSet(.password(password))
    }
    self.userCredential = userCredential
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.instance, forKey: .instance)
    try container.encode(self.database, forKey: .database)
    try container.encode(self.user, forKey: .user)
    try container.encode(self.sqlStatement, forKey: .sqlStatement)
    try container.encode(self.validateOnly, forKey: .validateOnly)

    if let choice = self.userCredential {
      switch choice {
      case .password(let value):
        try container.encode(value, forKey: .password)
      }
    }
  }

  /// Oneof field to support other credential mechanisms in future like
  /// SecretManager etc.
  public enum OneOf_UserCredential: Codable, Equatable, Sendable {
    /// Optional. The database native user’s password.
    case password(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.ExecuteSqlRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
