// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Export cluster request.
public struct ExportClusterRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the cluster.
  public var name: Swift.String = Swift.String()

  /// Required. Name of the database where the export command will be executed.
  /// Note - Value provided should be the same as expected from
  /// `SELECT current_database();` and NOT as a resource reference.
  public var database: Swift.String = Swift.String()

  /// Oneof field to support other destinations in future.
  public var destination: OneOf_Destination? = nil

  /// Required field to specify export file type and options.
  public var exportOptions: OneOf_ExportOptions? = nil

  /// Initialize a new instance of `ExportClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportClusterRequest().with { $0.gcsDestination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsDestination = "gcsDestination"
    case csvExportOptions = "csvExportOptions"
    case sqlExportOptions = "sqlExportOptions"
    case name = "name"
    case database = "database"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.database = try container.decode(Swift.String.self, forKey: .database)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsDestination = try container.decodeIfPresent(
      GcsDestination?.self, forKey: .gcsDestination)
    {
      try destinationCheckAndSet(.gcsDestination(gcsDestination))
    }
    self.destination = destination

    var exportOptions: OneOf_ExportOptions? = nil
    let exportOptionsCheckAndSet = {
      if exportOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'exportOptions'"))
      }
      exportOptions = $0
    }
    if let csvExportOptions = try container.decodeIfPresent(
      ExportClusterRequest.CsvExportOptions?.self, forKey: .csvExportOptions)
    {
      try exportOptionsCheckAndSet(.csvExportOptions(csvExportOptions))
    }
    if let sqlExportOptions = try container.decodeIfPresent(
      ExportClusterRequest.SqlExportOptions?.self, forKey: .sqlExportOptions)
    {
      try exportOptionsCheckAndSet(.sqlExportOptions(sqlExportOptions))
    }
    self.exportOptions = exportOptions
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.database, forKey: .database)

    if let choice = self.destination {
      switch choice {
      case .gcsDestination(let value):
        try container.encode(value, forKey: .gcsDestination)
      }
    }

    if let choice = self.exportOptions {
      switch choice {
      case .csvExportOptions(let value):
        try container.encode(value, forKey: .csvExportOptions)
      case .sqlExportOptions(let value):
        try container.encode(value, forKey: .sqlExportOptions)
      }
    }
  }

  /// Options for exporting data in CSV format.
  public struct CsvExportOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The SELECT query used to extract the data.
    public var selectQuery: Swift.String = Swift.String()

    /// Optional. Specifies the character that separates columns within each row
    /// (line) of the file. The default is comma. The value of this argument has
    /// to be a character in Hex ASCII Code.
    public var fieldDelimiter: Swift.String = Swift.String()

    /// Optional. Specifies the quoting character to be used when a data value is
    /// quoted. The default is double-quote. The value of this argument has to be
    /// a character in Hex ASCII Code.
    public var quoteCharacter: Swift.String = Swift.String()

    /// Optional. Specifies the character that should appear before a data
    /// character that needs to be escaped. The default is the same as quote
    /// character. The value of this argument has to be a character in Hex ASCII
    /// Code.
    public var escapeCharacter: Swift.String = Swift.String()

    /// Initialize a new instance of `CsvExportOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CsvExportOptions().with { $0.selectQuery = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.ExportClusterRequest.CsvExportOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Options for exporting data in SQL format.
  public struct SqlExportOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Tables to export from.
    public var tables: [Swift.String] = []

    /// Optional. If true, only export the schema.
    public var schemaOnly: Swift.Bool? = nil

    /// Optional. If true, output commands to DROP all the dumped database
    /// objects prior to outputting the commands for creating them.
    public var cleanTargetObjects: Swift.Bool? = nil

    /// Optional. If true, use DROP ... IF EXISTS commands to check for the
    /// object's existence before dropping it in clean_target_objects mode.
    public var ifExistTargetObjects: Swift.Bool? = nil

    /// Initialize a new instance of `SqlExportOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SqlExportOptions().with { $0.tables = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.ExportClusterRequest.SqlExportOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Oneof field to support other destinations in future.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Required. Option to export data to cloud storage.
    indirect case gcsDestination(GcsDestination?)
  }

  /// Required field to specify export file type and options.
  public enum OneOf_ExportOptions: Codable, Equatable, Sendable {
    /// Options for exporting data in CSV format. Required field to be set for
    /// CSV file type.
    indirect case csvExportOptions(ExportClusterRequest.CsvExportOptions?)
    /// Options for exporting data in SQL format. Required field to be set for
    /// SQL file type.
    indirect case sqlExportOptions(ExportClusterRequest.SqlExportOptions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.ExportClusterRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
