// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message for requests to generate a client certificate signed by the Cluster
/// CA.
public struct GenerateClientCertificateRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the parent resource. The required format is:
  ///  * projects/{project}/locations/{location}/clusters/{cluster}
  public var parent: Swift.String = Swift.String()

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server ignores the
  /// request if it has already been completed. The server guarantees that for at
  /// least 60 minutes since the first request.
  ///
  /// For example, consider a situation where you make an initial request and
  /// the request times out. If you make the request again with the same request
  /// ID, the server can check if the original operation with the same request ID
  /// was received, and if so, ignores the second request. This prevents
  /// clients from accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Optional. An optional hint to the endpoint to generate the client
  /// certificate with the requested duration. The duration can be from 1 hour to
  /// 24 hours. The endpoint may or may not honor the hint. If the hint is left
  /// unspecified or is not honored, then the endpoint will pick an appropriate
  /// default duration.
  public var certDuration: GoogleCloudWkt.Duration? = nil

  /// Optional. The public key from the client.
  public var publicKey: Swift.String = Swift.String()

  /// Optional. An optional hint to the endpoint to generate a client certificate
  /// that can be used by AlloyDB connectors to exchange additional metadata with
  /// the server after TLS handshake.
  public var useMetadataExchange: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `GenerateClientCertificateRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateClientCertificateRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.GenerateClientCertificateRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
