// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// An Instance is a computing unit that an end customer can connect to.
/// It's the main unit of computing resources in AlloyDB.
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the instance resource with the format:
  ///  * projects/{project}/locations/{region}/clusters/{cluster_id}/instances/{instance_id}
  /// where the cluster and instance ID segments should satisfy the regex
  /// expression `[a-z]([a-z0-9-]{0,61}[a-z0-9])?`, e.g. 1-63 characters of
  /// lowercase letters, numbers, and dashes, starting with a letter, and ending
  /// with a letter or number. For more details see https://google.aip.dev/122.
  /// The prefix of the instance resource name is the name of the parent
  /// resource:
  ///  * projects/{project}/locations/{region}/clusters/{cluster_id}
  public var name: Swift.String = Swift.String()

  /// User-settable and human-readable display name for the Instance.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The system-generated UID of the resource. The UID is assigned
  /// when the resource is created, and it is retained until it is deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. Create time stamp
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Update time stamp
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. Delete time stamp
  public var deleteTime: GoogleWKT.Timestamp? = nil

  /// Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The current serving state of the instance.
  public var state: Instance.State = Instance.State()

  /// Required. The type of the instance. Specified at creation time.
  public var instanceType: Instance.InstanceType = Instance.InstanceType()

  /// Configurations for the machines that host the underlying
  /// database engine.
  public var machineConfig: Instance.MachineConfig? = nil

  /// Availability type of an Instance.
  /// If empty, defaults to REGIONAL for primary instances.
  /// For read pools, availability_type is always UNSPECIFIED. Instances in the
  /// read pools are evenly distributed across available zones within the region
  /// (i.e. read pools with more than one node will have a node in at
  /// least two zones).
  public var availabilityType: Instance.AvailabilityType = Instance.AvailabilityType()

  /// The Compute Engine zone that the instance should serve from, per
  /// https://cloud.google.com/compute/docs/regions-zones
  /// This can ONLY be specified for ZONAL instances.
  /// If present for a REGIONAL instance, an error will be thrown.
  /// If this is absent for a ZONAL instance, instance is created in a random
  /// zone with available capacity.
  public var gceZone: Swift.String = Swift.String()

  /// Database flags. Set at the instance level.
  /// They are copied from the primary instance on secondary instance creation.
  /// Flags that have restrictions default to the value at primary
  /// instance on read instances during creation. Read instances can set new
  /// flags or override existing flags that are relevant for reads, for example,
  /// for enabling columnar cache on a read instance. Flags set on read instance
  /// might or might not be present on the primary instance.
  ///
  ///
  /// This is a list of "key": "value" pairs.
  /// "key": The name of the flag. These flags are passed at instance setup time,
  /// so include both server options and system variables for Postgres. Flags are
  /// specified with underscores, not hyphens.
  /// "value": The value of the flag. Booleans are set to **on** for true
  /// and **off** for false. This field must be omitted if the flag
  /// doesn't take a value.
  public var databaseFlags: [Swift.String: Swift.String] = [:]

  /// Output only. This is set for the read-write VM of the PRIMARY instance
  /// only.
  public var writableNode: Instance.Node? = nil

  /// Output only. List of available read-only VMs in this instance, including
  /// the standby for a PRIMARY instance.
  public var nodes: [Instance.Node] = []

  /// Configuration for query insights.
  public var queryInsightsConfig: Instance.QueryInsightsInstanceConfig? = nil

  /// Configuration for observability.
  public var observabilityConfig: Instance.ObservabilityInstanceConfig? = nil

  /// Read pool instance configuration.
  /// This is required if the value of instanceType is READ_POOL.
  public var readPoolConfig: Instance.ReadPoolConfig? = nil

  /// Output only. The IP address for the Instance.
  /// This is the connection endpoint for an end-user application.
  public var ipAddress: Swift.String = Swift.String()

  /// Output only. The public IP addresses for the Instance. This is available
  /// ONLY when enable_public_ip is set. This is the connection endpoint for an
  /// end-user application.
  public var publicIpAddress: Swift.String = Swift.String()

  /// Output only. Reconciling (https://google.aip.dev/128#reconciliation).
  /// Set to true if the current state of Instance does not match the user's
  /// intended state, and the service is actively updating the resource to
  /// reconcile them. This can happen due to user-triggered updates or
  /// system actions like failover or maintenance.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// For Resource freshness validation (https://google.aip.dev/154)
  public var etag: Swift.String = Swift.String()

  /// Annotations to allow client tools to store small amount of arbitrary data.
  /// This is distinct from labels.
  /// https://google.aip.dev/128
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Client connection specific configurations
  public var clientConnectionConfig: Instance.ClientConnectionConfig? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Optional. The configuration for Private Service Connect (PSC) for the
  /// instance.
  public var pscInstanceConfig: Instance.PscInstanceConfig? = nil

  /// Optional. Instance-level network configuration.
  public var networkConfig: Instance.InstanceNetworkConfig? = nil

  /// Output only. All outbound public IP addresses configured for the instance.
  public var outboundPublicIpAddresses: [Swift.String] = []

  /// Optional. Specifies whether an instance needs to spin up. Once the instance
  /// is active, the activation policy can be updated to the `NEVER` to stop the
  /// instance. Likewise, the activation policy can be updated to `ALWAYS` to
  /// start the instance.
  /// There are restrictions around when an instance can/cannot be activated (for
  /// example, a read pool instance should be stopped before stopping primary
  /// etc.). Please refer to the API documentation for more details.
  public var activationPolicy: Instance.ActivationPolicy = Instance.ActivationPolicy()

  /// Optional. The configuration for Managed Connection Pool (MCP).
  public var connectionPoolConfig: Instance.ConnectionPoolConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let state = CodingKeys(stringValue: "state")
    static let instanceType = CodingKeys(stringValue: "instanceType")
    static let machineConfig = CodingKeys(stringValue: "machineConfig")
    static let availabilityType = CodingKeys(stringValue: "availabilityType")
    static let gceZone = CodingKeys(stringValue: "gceZone")
    static let databaseFlags = CodingKeys(stringValue: "databaseFlags")
    static let writableNode = CodingKeys(stringValue: "writableNode")
    static let nodes = CodingKeys(stringValue: "nodes")
    static let queryInsightsConfig = CodingKeys(stringValue: "queryInsightsConfig")
    static let observabilityConfig = CodingKeys(stringValue: "observabilityConfig")
    static let readPoolConfig = CodingKeys(stringValue: "readPoolConfig")
    static let ipAddress = CodingKeys(stringValue: "ipAddress")
    static let publicIpAddress = CodingKeys(stringValue: "publicIpAddress")
    static let reconciling = CodingKeys(stringValue: "reconciling")
    static let etag = CodingKeys(stringValue: "etag")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let clientConnectionConfig = CodingKeys(stringValue: "clientConnectionConfig")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let pscInstanceConfig = CodingKeys(stringValue: "pscInstanceConfig")
    static let networkConfig = CodingKeys(stringValue: "networkConfig")
    static let outboundPublicIpAddresses = CodingKeys(stringValue: "outboundPublicIpAddresses")
    static let activationPolicy = CodingKeys(stringValue: "activationPolicy")
    static let connectionPoolConfig = CodingKeys(stringValue: "connectionPoolConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "uid",
      "createTime",
      "updateTime",
      "deleteTime",
      "labels",
      "state",
      "instanceType",
      "machineConfig",
      "availabilityType",
      "gceZone",
      "databaseFlags",
      "writableNode",
      "nodes",
      "queryInsightsConfig",
      "observabilityConfig",
      "readPoolConfig",
      "ipAddress",
      "publicIpAddress",
      "reconciling",
      "etag",
      "annotations",
      "clientConnectionConfig",
      "satisfiesPzs",
      "pscInstanceConfig",
      "networkConfig",
      "outboundPublicIpAddresses",
      "activationPolicy",
      "connectionPoolConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Instance.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Instance.InstanceType.self, forKey: .instanceType)
    {
      self.instanceType = value
    }
    self.machineConfig = try container.decodeIfPresent(
      Instance.MachineConfig.self, forKey: .machineConfig)
    if let value = try container.decodeIfPresent(
      Instance.AvailabilityType.self, forKey: .availabilityType)
    {
      self.availabilityType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gceZone) {
      self.gceZone = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .databaseFlags)
    {
      self.databaseFlags = value
    }
    self.writableNode = try container.decodeIfPresent(Instance.Node.self, forKey: .writableNode)
    if let value = try container.decodeIfPresent([Instance.Node].self, forKey: .nodes) {
      self.nodes = value
    }
    self.queryInsightsConfig = try container.decodeIfPresent(
      Instance.QueryInsightsInstanceConfig.self, forKey: .queryInsightsConfig)
    self.observabilityConfig = try container.decodeIfPresent(
      Instance.ObservabilityInstanceConfig.self, forKey: .observabilityConfig)
    self.readPoolConfig = try container.decodeIfPresent(
      Instance.ReadPoolConfig.self, forKey: .readPoolConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
      self.ipAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .publicIpAddress) {
      self.publicIpAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reconciling) {
      self.reconciling = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    self.clientConnectionConfig = try container.decodeIfPresent(
      Instance.ClientConnectionConfig.self, forKey: .clientConnectionConfig)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs) {
      self.satisfiesPzs = value
    }
    self.pscInstanceConfig = try container.decodeIfPresent(
      Instance.PscInstanceConfig.self, forKey: .pscInstanceConfig)
    self.networkConfig = try container.decodeIfPresent(
      Instance.InstanceNetworkConfig.self, forKey: .networkConfig)
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .outboundPublicIpAddresses)
    {
      self.outboundPublicIpAddresses = value
    }
    if let value = try container.decodeIfPresent(
      Instance.ActivationPolicy.self, forKey: .activationPolicy)
    {
      self.activationPolicy = value
    }
    self.connectionPoolConfig = try container.decodeIfPresent(
      Instance.ConnectionPoolConfig.self, forKey: .connectionPoolConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.instanceType, forKey: .instanceType)
    try container.encodeIfPresent(self.machineConfig, forKey: .machineConfig)
    try container.encode(self.availabilityType, forKey: .availabilityType)
    try container.encode(self.gceZone, forKey: .gceZone)
    try container.encode(self.databaseFlags, forKey: .databaseFlags)
    try container.encodeIfPresent(self.writableNode, forKey: .writableNode)
    try container.encode(self.nodes, forKey: .nodes)
    try container.encodeIfPresent(self.queryInsightsConfig, forKey: .queryInsightsConfig)
    try container.encodeIfPresent(self.observabilityConfig, forKey: .observabilityConfig)
    try container.encodeIfPresent(self.readPoolConfig, forKey: .readPoolConfig)
    try container.encode(self.ipAddress, forKey: .ipAddress)
    try container.encode(self.publicIpAddress, forKey: .publicIpAddress)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encodeIfPresent(self.clientConnectionConfig, forKey: .clientConnectionConfig)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encodeIfPresent(self.pscInstanceConfig, forKey: .pscInstanceConfig)
    try container.encodeIfPresent(self.networkConfig, forKey: .networkConfig)
    try container.encode(self.outboundPublicIpAddresses, forKey: .outboundPublicIpAddresses)
    try container.encode(self.activationPolicy, forKey: .activationPolicy)
    try container.encodeIfPresent(self.connectionPoolConfig, forKey: .connectionPoolConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// MachineConfig describes the configuration of a machine.
  public struct MachineConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The number of CPU's in the VM instance.
    public var cpuCount: Swift.Int32 = Swift.Int32()

    /// Machine type of the VM instance. E.g. "n2-highmem-4",
    /// "n2-highmem-8", "c4a-highmem-4-lssd".
    /// cpu_count must match the number of vCPUs in the machine type.
    public var machineType: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MachineConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MachineConfig().with { $0.cpuCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cpuCount = CodingKeys(stringValue: "cpuCount")
      static let machineType = CodingKeys(stringValue: "machineType")

      static let _knownKeys: Set<Swift.String> = [
        "cpuCount",
        "machineType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .cpuCount) {
        self.cpuCount = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineType) {
        self.machineType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cpuCount, forKey: .cpuCount)
      try container.encode(self.machineType, forKey: .machineType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.MachineConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Details of a single node in the instance.
  /// Nodes in an AlloyDB instance are ephemeral, they can change during
  /// update, failover, autohealing and resize operations.
  public struct Node: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The Compute Engine zone of the VM e.g. "us-central1-b".
    public var zoneId: Swift.String = Swift.String()

    /// Output only. The identifier of the VM e.g.
    /// "test-read-0601-407e52be-ms3l".
    public var id: Swift.String = Swift.String()

    /// Output only. The private IP address of the VM e.g. "10.57.0.34".
    public var ip: Swift.String = Swift.String()

    /// Output only. Determined by state of the compute VM and postgres-service
    /// health. Compute VM state can have values listed in
    /// https://cloud.google.com/compute/docs/instances/instance-life-cycle and
    /// postgres-service health can have values: HEALTHY and UNHEALTHY.
    public var state: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Node`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Node().with { $0.zoneId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let zoneId = CodingKeys(stringValue: "zoneId")
      static let id = CodingKeys(stringValue: "id")
      static let ip = CodingKeys(stringValue: "ip")
      static let state = CodingKeys(stringValue: "state")

      static let _knownKeys: Set<Swift.String> = [
        "zoneId",
        "id",
        "ip",
        "state",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .zoneId) {
        self.zoneId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ip) {
        self.ip = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .state) {
        self.state = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.zoneId, forKey: .zoneId)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.ip, forKey: .ip)
      try container.encode(self.state, forKey: .state)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.Node"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// QueryInsights Instance specific configuration.
  public struct QueryInsightsInstanceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Record application tags for an instance.
    /// This flag is turned "on" by default.
    public var recordApplicationTags: Swift.Bool? = nil

    /// Record client address for an instance. Client address is PII information.
    /// This flag is turned "on" by default.
    public var recordClientAddress: Swift.Bool? = nil

    /// Query string length. The default value is 1024.
    /// Any integer between 256 and 4500 is considered valid.
    public var queryStringLength: Swift.UInt32 = Swift.UInt32()

    /// Number of query execution plans captured by Insights per minute
    /// for all queries combined. The default value is 5.
    /// Any integer between 0 and 20 is considered valid.
    public var queryPlansPerMinute: Swift.UInt32? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `QueryInsightsInstanceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QueryInsightsInstanceConfig().with { $0.recordApplicationTags = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let recordApplicationTags = CodingKeys(stringValue: "recordApplicationTags")
      static let recordClientAddress = CodingKeys(stringValue: "recordClientAddress")
      static let queryStringLength = CodingKeys(stringValue: "queryStringLength")
      static let queryPlansPerMinute = CodingKeys(stringValue: "queryPlansPerMinute")

      static let _knownKeys: Set<Swift.String> = [
        "recordApplicationTags",
        "recordClientAddress",
        "queryStringLength",
        "queryPlansPerMinute",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.recordApplicationTags = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .recordApplicationTags)
      self.recordClientAddress = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .recordClientAddress)
      if let value = try container.decodeIfPresent(Swift.UInt32.self, forKey: .queryStringLength) {
        self.queryStringLength = value
      }
      self.queryPlansPerMinute = try container.decodeIfPresent(
        Swift.UInt32.self, forKey: .queryPlansPerMinute)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.recordApplicationTags, forKey: .recordApplicationTags)
      try container.encodeIfPresent(self.recordClientAddress, forKey: .recordClientAddress)
      try container.encode(self.queryStringLength, forKey: .queryStringLength)
      try container.encodeIfPresent(self.queryPlansPerMinute, forKey: .queryPlansPerMinute)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.QueryInsightsInstanceConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Observability Instance specific configuration.
  public struct ObservabilityInstanceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Observability feature status for an instance.
    /// This flag is turned "off" by default.
    public var enabled: Swift.Bool? = nil

    /// Preserve comments in query string for an instance.
    /// This flag is turned "off" by default.
    public var preserveComments: Swift.Bool? = nil

    /// Track wait events during query execution for an instance.
    /// This flag is turned "on" by default but tracking is enabled only after
    /// observability enabled flag is also turned on.
    public var trackWaitEvents: Swift.Bool? = nil

    /// Output only. Track wait event types during query execution for an
    /// instance. This flag is turned "on" by default but tracking is enabled
    /// only after observability enabled flag is also turned on. This is
    /// read-only flag and only modifiable by internal API.
    public var trackWaitEventTypes: Swift.Bool? = nil

    /// Query string length. The default value is 10k.
    public var maxQueryStringLength: Swift.Int32? = nil

    /// Record application tags for an instance.
    /// This flag is turned "off" by default.
    public var recordApplicationTags: Swift.Bool? = nil

    /// Number of query execution plans captured by Insights per minute
    /// for all queries combined. The default value is 200.
    /// Any integer between 0 to 200 is considered valid.
    public var queryPlansPerMinute: Swift.Int32? = nil

    /// Track actively running queries on the instance.
    /// If not set, this flag is "off" by default.
    public var trackActiveQueries: Swift.Bool? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ObservabilityInstanceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ObservabilityInstanceConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enabled = CodingKeys(stringValue: "enabled")
      static let preserveComments = CodingKeys(stringValue: "preserveComments")
      static let trackWaitEvents = CodingKeys(stringValue: "trackWaitEvents")
      static let trackWaitEventTypes = CodingKeys(stringValue: "trackWaitEventTypes")
      static let maxQueryStringLength = CodingKeys(stringValue: "maxQueryStringLength")
      static let recordApplicationTags = CodingKeys(stringValue: "recordApplicationTags")
      static let queryPlansPerMinute = CodingKeys(stringValue: "queryPlansPerMinute")
      static let trackActiveQueries = CodingKeys(stringValue: "trackActiveQueries")

      static let _knownKeys: Set<Swift.String> = [
        "enabled",
        "preserveComments",
        "trackWaitEvents",
        "trackWaitEventTypes",
        "maxQueryStringLength",
        "recordApplicationTags",
        "queryPlansPerMinute",
        "trackActiveQueries",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.enabled = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled)
      self.preserveComments = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .preserveComments)
      self.trackWaitEvents = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .trackWaitEvents)
      self.trackWaitEventTypes = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .trackWaitEventTypes)
      self.maxQueryStringLength = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .maxQueryStringLength)
      self.recordApplicationTags = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .recordApplicationTags)
      self.queryPlansPerMinute = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .queryPlansPerMinute)
      self.trackActiveQueries = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .trackActiveQueries)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.enabled, forKey: .enabled)
      try container.encodeIfPresent(self.preserveComments, forKey: .preserveComments)
      try container.encodeIfPresent(self.trackWaitEvents, forKey: .trackWaitEvents)
      try container.encodeIfPresent(self.trackWaitEventTypes, forKey: .trackWaitEventTypes)
      try container.encodeIfPresent(self.maxQueryStringLength, forKey: .maxQueryStringLength)
      try container.encodeIfPresent(self.recordApplicationTags, forKey: .recordApplicationTags)
      try container.encodeIfPresent(self.queryPlansPerMinute, forKey: .queryPlansPerMinute)
      try container.encodeIfPresent(self.trackActiveQueries, forKey: .trackActiveQueries)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.ObservabilityInstanceConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for a read pool instance.
  public struct ReadPoolConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Read capacity, i.e. number of nodes in a read pool instance.
    public var nodeCount: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ReadPoolConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReadPoolConfig().with { $0.nodeCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let nodeCount = CodingKeys(stringValue: "nodeCount")

      static let _knownKeys: Set<Swift.String> = [
        "nodeCount"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .nodeCount) {
        self.nodeCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.nodeCount, forKey: .nodeCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.ReadPoolConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Client connection configuration
  public struct ClientConnectionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Configuration to enforce connectors only (ex: AuthProxy)
    /// connections to the database.
    public var requireConnectors: Swift.Bool = Swift.Bool()

    /// Optional. SSL configuration option for this instance.
    public var sslConfig: SslConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ClientConnectionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClientConnectionConfig().with { $0.requireConnectors = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let requireConnectors = CodingKeys(stringValue: "requireConnectors")
      static let sslConfig = CodingKeys(stringValue: "sslConfig")

      static let _knownKeys: Set<Swift.String> = [
        "requireConnectors",
        "sslConfig",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requireConnectors) {
        self.requireConnectors = value
      }
      self.sslConfig = try container.decodeIfPresent(SslConfig.self, forKey: .sslConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.requireConnectors, forKey: .requireConnectors)
      try container.encodeIfPresent(self.sslConfig, forKey: .sslConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.ClientConnectionConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for setting up a PSC interface to enable outbound
  /// connectivity.
  public struct PscInterfaceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The network attachment resource created in the consumer network to which
    /// the PSC interface will be linked. This is of the format:
    /// "projects/${CONSUMER_PROJECT}/regions/${REGION}/networkAttachments/${NETWORK_ATTACHMENT_NAME}".
    /// The network attachment must be in the same region as the instance.
    public var networkAttachmentResource: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PscInterfaceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscInterfaceConfig().with { $0.networkAttachmentResource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let networkAttachmentResource = CodingKeys(stringValue: "networkAttachmentResource")

      static let _knownKeys: Set<Swift.String> = [
        "networkAttachmentResource"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .networkAttachmentResource)
      {
        self.networkAttachmentResource = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.networkAttachmentResource, forKey: .networkAttachmentResource)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.PscInterfaceConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for setting up PSC service automation. Consumer projects in
  /// the configs will be allowlisted automatically for the instance.
  public struct PscAutoConnectionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The consumer project to which the PSC service automation endpoint will
    /// be created.
    public var consumerProject: Swift.String = Swift.String()

    /// The consumer network for the PSC service automation, example:
    /// "projects/vpc-host-project/global/networks/default".
    /// The consumer network might be hosted a different project than the
    /// consumer project.
    public var consumerNetwork: Swift.String = Swift.String()

    /// Output only. The IP address of the PSC service automation endpoint.
    public var ipAddress: Swift.String = Swift.String()

    /// Output only. The status of the PSC service automation connection.
    /// Possible values:
    ///   "STATE_UNSPECIFIED" - An invalid state as the default case.
    ///   "ACTIVE" - The connection has been created successfully.
    ///   "FAILED" - The connection is not functional since some resources on the
    /// connection fail to be created.
    ///   "CREATING" - The connection is being created.
    ///   "DELETING" - The connection is being deleted.
    ///   "CREATE_REPAIRING" - The connection is being repaired to complete
    /// creation.
    ///   "DELETE_REPAIRING" - The connection is being repaired to complete
    /// deletion.
    public var status: Swift.String = Swift.String()

    /// Output only. The status of the service connection policy.
    /// Possible values:
    ///   "STATE_UNSPECIFIED" - Default state, when Connection Map is created
    /// initially.
    ///   "VALID" - Set when policy and map configuration is valid, and their
    /// matching can lead to allowing creation of PSC Connections subject to
    /// other constraints like connections limit.
    ///   "CONNECTION_POLICY_MISSING" - No Service Connection Policy found for
    /// this network and Service Class
    ///   "POLICY_LIMIT_REACHED" - Service Connection Policy limit reached for
    ///   this network and Service Class
    ///   "CONSUMER_INSTANCE_PROJECT_NOT_ALLOWLISTED" - The consumer instance
    /// project is not in AllowedGoogleProducersResourceHierarchyLevels of the
    /// matching ServiceConnectionPolicy.
    public var consumerNetworkStatus: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PscAutoConnectionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscAutoConnectionConfig().with { $0.consumerProject = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let consumerProject = CodingKeys(stringValue: "consumerProject")
      static let consumerNetwork = CodingKeys(stringValue: "consumerNetwork")
      static let ipAddress = CodingKeys(stringValue: "ipAddress")
      static let status = CodingKeys(stringValue: "status")
      static let consumerNetworkStatus = CodingKeys(stringValue: "consumerNetworkStatus")

      static let _knownKeys: Set<Swift.String> = [
        "consumerProject",
        "consumerNetwork",
        "ipAddress",
        "status",
        "consumerNetworkStatus",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .consumerProject) {
        self.consumerProject = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .consumerNetwork) {
        self.consumerNetwork = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
        self.ipAddress = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .status) {
        self.status = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .consumerNetworkStatus)
      {
        self.consumerNetworkStatus = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.consumerProject, forKey: .consumerProject)
      try container.encode(self.consumerNetwork, forKey: .consumerNetwork)
      try container.encode(self.ipAddress, forKey: .ipAddress)
      try container.encode(self.status, forKey: .status)
      try container.encode(self.consumerNetworkStatus, forKey: .consumerNetworkStatus)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.PscAutoConnectionConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// PscInstanceConfig contains PSC related configuration at an
  /// instance level.
  public struct PscInstanceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The service attachment created when Private
    /// Service Connect (PSC) is enabled for the instance.
    /// The name of the resource will be in the format of
    /// `projects/<alloydb-tenant-project-number>/regions/<region-name>/serviceAttachments/<service-attachment-name>`
    public var serviceAttachmentLink: Swift.String = Swift.String()

    /// Optional. List of consumer projects that are allowed to create
    /// PSC endpoints to service-attachments to this instance.
    public var allowedConsumerProjects: [Swift.String] = []

    /// Output only. The DNS name of the instance for PSC connectivity.
    /// Name convention: <uid>.<uid>.<region>.alloydb-psc.goog
    public var pscDnsName: Swift.String = Swift.String()

    /// Optional. Configurations for setting up PSC interfaces attached to the
    /// instance which are used for outbound connectivity. Only primary instances
    /// can have PSC interface attached. Currently we only support 0 or 1 PSC
    /// interface.
    public var pscInterfaceConfigs: [Instance.PscInterfaceConfig] = []

    /// Optional. Configurations for setting up PSC service automation.
    public var pscAutoConnections: [Instance.PscAutoConnectionConfig] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PscInstanceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscInstanceConfig().with { $0.serviceAttachmentLink = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let serviceAttachmentLink = CodingKeys(stringValue: "serviceAttachmentLink")
      static let allowedConsumerProjects = CodingKeys(stringValue: "allowedConsumerProjects")
      static let pscDnsName = CodingKeys(stringValue: "pscDnsName")
      static let pscInterfaceConfigs = CodingKeys(stringValue: "pscInterfaceConfigs")
      static let pscAutoConnections = CodingKeys(stringValue: "pscAutoConnections")

      static let _knownKeys: Set<Swift.String> = [
        "serviceAttachmentLink",
        "allowedConsumerProjects",
        "pscDnsName",
        "pscInterfaceConfigs",
        "pscAutoConnections",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .serviceAttachmentLink)
      {
        self.serviceAttachmentLink = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .allowedConsumerProjects)
      {
        self.allowedConsumerProjects = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pscDnsName) {
        self.pscDnsName = value
      }
      if let value = try container.decodeIfPresent(
        [Instance.PscInterfaceConfig].self, forKey: .pscInterfaceConfigs)
      {
        self.pscInterfaceConfigs = value
      }
      if let value = try container.decodeIfPresent(
        [Instance.PscAutoConnectionConfig].self, forKey: .pscAutoConnections)
      {
        self.pscAutoConnections = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.serviceAttachmentLink, forKey: .serviceAttachmentLink)
      try container.encode(self.allowedConsumerProjects, forKey: .allowedConsumerProjects)
      try container.encode(self.pscDnsName, forKey: .pscDnsName)
      try container.encode(self.pscInterfaceConfigs, forKey: .pscInterfaceConfigs)
      try container.encode(self.pscAutoConnections, forKey: .pscAutoConnections)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.PscInstanceConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Metadata related to instance-level network configuration.
  public struct InstanceNetworkConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. A list of external network authorized to access this instance.
    public var authorizedExternalNetworks: [Instance.InstanceNetworkConfig.AuthorizedNetwork] = []

    /// Optional. Enabling public ip for the instance.
    public var enablePublicIp: Swift.Bool = Swift.Bool()

    /// Optional. Enabling an outbound public IP address to support a database
    /// server sending requests out into the internet.
    public var enableOutboundPublicIp: Swift.Bool = Swift.Bool()

    /// Output only. The resource link for the VPC network in which instance
    /// resources are created and from which they are accessible via Private IP.
    /// This will be the same value as the parent cluster's network. It is
    /// specified in the form: //
    /// `projects/{project_number}/global/networks/{network_id}`.
    public var network: Swift.String = Swift.String()

    /// Optional. Name of the allocated IP range for the private IP AlloyDB
    /// instance, for example: "google-managed-services-default". If set, the
    /// instance IPs will be created from this allocated range and will override
    /// the IP range used by the parent cluster. The range name must comply with
    /// [RFC 1035](http://datatracker.ietf.org/doc/html/rfc1035). Specifically,
    /// the name must be 1-63 characters long and match the regular expression
    /// [a-z]([-a-z0-9]*[a-z0-9])?.
    public var allocatedIpRangeOverride: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InstanceNetworkConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceNetworkConfig().with { $0.authorizedExternalNetworks = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let authorizedExternalNetworks = CodingKeys(stringValue: "authorizedExternalNetworks")
      static let enablePublicIp = CodingKeys(stringValue: "enablePublicIp")
      static let enableOutboundPublicIp = CodingKeys(stringValue: "enableOutboundPublicIp")
      static let network = CodingKeys(stringValue: "network")
      static let allocatedIpRangeOverride = CodingKeys(stringValue: "allocatedIpRangeOverride")

      static let _knownKeys: Set<Swift.String> = [
        "authorizedExternalNetworks",
        "enablePublicIp",
        "enableOutboundPublicIp",
        "network",
        "allocatedIpRangeOverride",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Instance.InstanceNetworkConfig.AuthorizedNetwork].self, forKey: .authorizedExternalNetworks
      ) {
        self.authorizedExternalNetworks = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enablePublicIp) {
        self.enablePublicIp = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableOutboundPublicIp)
      {
        self.enableOutboundPublicIp = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
        self.network = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .allocatedIpRangeOverride)
      {
        self.allocatedIpRangeOverride = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.authorizedExternalNetworks, forKey: .authorizedExternalNetworks)
      try container.encode(self.enablePublicIp, forKey: .enablePublicIp)
      try container.encode(self.enableOutboundPublicIp, forKey: .enableOutboundPublicIp)
      try container.encode(self.network, forKey: .network)
      try container.encode(self.allocatedIpRangeOverride, forKey: .allocatedIpRangeOverride)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// AuthorizedNetwork contains metadata for an authorized network.
    public struct AuthorizedNetwork: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// CIDR range for one authorzied network of the instance.
      public var cidrRange: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `AuthorizedNetwork`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = AuthorizedNetwork().with { $0.cidrRange = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let cidrRange = CodingKeys(stringValue: "cidrRange")

        static let _knownKeys: Set<Swift.String> = [
          "cidrRange"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cidrRange) {
          self.cidrRange = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.cidrRange, forKey: .cidrRange)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.alloydb.v1.Instance.InstanceNetworkConfig.AuthorizedNetwork"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.InstanceNetworkConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for Managed Connection Pool (MCP).
  public struct ConnectionPoolConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Whether to enable Managed Connection Pool (MCP).
    public var enabled: Swift.Bool = Swift.Bool()

    /// Optional. Connection Pool flags, as a list of "key": "value" pairs.
    public var flags: [Swift.String: Swift.String] = [:]

    /// Output only. The number of running poolers per instance.
    public var poolerCount: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConnectionPoolConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConnectionPoolConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enabled = CodingKeys(stringValue: "enabled")
      static let flags = CodingKeys(stringValue: "flags")
      static let poolerCount = CodingKeys(stringValue: "poolerCount")

      static let _knownKeys: Set<Swift.String> = [
        "enabled",
        "flags",
        "poolerCount",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled) {
        self.enabled = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .flags)
      {
        self.flags = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .poolerCount) {
        self.poolerCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enabled, forKey: .enabled)
      try container.encode(self.flags, forKey: .flags)
      try container.encode(self.poolerCount, forKey: .poolerCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.ConnectionPoolConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Instance State
  public enum State: Codable, Equatable, Sendable {
    /// The state of the instance is unknown.
    case unspecified
    /// The instance is active and running.
    case ready
    /// The instance is stopped. Instance name and IP resources are preserved.
    case stopped
    /// The instance is being created.
    case creating
    /// The instance is being deleted.
    case deleting
    /// The instance is down for maintenance.
    case maintenance
    /// The creation of the instance failed or a fatal error occurred during
    /// an operation on the instance.
    /// Note: Instances in this state would tried to be auto-repaired. And
    /// Customers should be able to restart, update or delete these instances.
    case failed
    /// Index 7 is used in the producer apis for ROLLED_BACK state. Keeping that
    /// index unused in case that state also needs to exposed via consumer apis
    /// in future.
    /// The instance has been configured to sync data from some other source.
    case bootstrapping
    /// The instance is being promoted.
    case promoting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ready: return 1
      case .stopped: return 2
      case .creating: return 3
      case .deleting: return 4
      case .maintenance: return 5
      case .failed: return 6
      case .bootstrapping: return 8
      case .promoting: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .ready: return "READY"
      case .stopped: return "STOPPED"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .maintenance: return "MAINTENANCE"
      case .failed: return "FAILED"
      case .bootstrapping: return "BOOTSTRAPPING"
      case .promoting: return "PROMOTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "READY": self = .ready
      case "STOPPED": self = .stopped
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "MAINTENANCE": self = .maintenance
      case "FAILED": self = .failed
      case "BOOTSTRAPPING": self = .bootstrapping
      case "PROMOTING": self = .promoting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ready
      case 2: self = .stopped
      case 3: self = .creating
      case 4: self = .deleting
      case 5: self = .maintenance
      case 6: self = .failed
      case 8: self = .bootstrapping
      case 9: self = .promoting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .ready: return try container.encode("READY")
      case .stopped: return try container.encode("STOPPED")
      case .creating: return try container.encode("CREATING")
      case .deleting: return try container.encode("DELETING")
      case .maintenance: return try container.encode("MAINTENANCE")
      case .failed: return try container.encode("FAILED")
      case .bootstrapping: return try container.encode("BOOTSTRAPPING")
      case .promoting: return try container.encode("PROMOTING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of an Instance
  public enum InstanceType: Codable, Equatable, Sendable {
    /// The type of the instance is unknown.
    case unspecified
    /// PRIMARY instances support read and write operations.
    case primary
    /// READ POOL instances support read operations only. Each read pool instance
    /// consists of one or more homogeneous nodes.
    ///  * Read pool of size 1 can only have zonal availability.
    ///  * Read pools with node count of 2 or more can have regional
    ///    availability (nodes are present in 2 or more zones in a region).
    case readPool
    /// SECONDARY instances support read operations only. SECONDARY instance
    /// is a cross-region read replica
    case secondary
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .primary: return 1
      case .readPool: return 2
      case .secondary: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INSTANCE_TYPE_UNSPECIFIED"
      case .primary: return "PRIMARY"
      case .readPool: return "READ_POOL"
      case .secondary: return "SECONDARY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InstanceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INSTANCE_TYPE_UNSPECIFIED": self = .unspecified
      case "PRIMARY": self = .primary
      case "READ_POOL": self = .readPool
      case "SECONDARY": self = .secondary
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InstanceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .primary
      case 2: self = .readPool
      case 3: self = .secondary
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("INSTANCE_TYPE_UNSPECIFIED")
      case .primary: return try container.encode("PRIMARY")
      case .readPool: return try container.encode("READ_POOL")
      case .secondary: return try container.encode("SECONDARY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The Availability type of an instance. Potential values:
  ///
  /// - ZONAL: The instance serves data from only one zone. Outages in that
  ///     zone affect instance availability.
  /// - REGIONAL: The instance can serve data from more than one zone in a
  ///     region (it is highly available).
  public enum AvailabilityType: Codable, Equatable, Sendable {
    /// This is an unknown Availability type.
    case unspecified
    /// Zonal available instance.
    case zonal
    /// Regional (or Highly) available instance.
    case regional
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .zonal: return 1
      case .regional: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AVAILABILITY_TYPE_UNSPECIFIED"
      case .zonal: return "ZONAL"
      case .regional: return "REGIONAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AvailabilityType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AVAILABILITY_TYPE_UNSPECIFIED": self = .unspecified
      case "ZONAL": self = .zonal
      case "REGIONAL": self = .regional
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AvailabilityType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .zonal
      case 2: self = .regional
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("AVAILABILITY_TYPE_UNSPECIFIED")
      case .zonal: return try container.encode("ZONAL")
      case .regional: return try container.encode("REGIONAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Specifies whether an instance needs to spin up.
  public enum ActivationPolicy: Codable, Equatable, Sendable {
    /// The policy is not specified.
    case unspecified
    /// The instance is running.
    case always
    /// The instance is not running.
    case never
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .always: return 1
      case .never: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACTIVATION_POLICY_UNSPECIFIED"
      case .always: return "ALWAYS"
      case .never: return "NEVER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ActivationPolicy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACTIVATION_POLICY_UNSPECIFIED": self = .unspecified
      case "ALWAYS": self = .always
      case "NEVER": self = .never
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ActivationPolicy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .always
      case 2: self = .never
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ACTIVATION_POLICY_UNSPECIFIED")
      case .always: return try container.encode("ALWAYS")
      case .never: return try container.encode("NEVER")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.Instance"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
