// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An Instance is a computing unit that an end customer can connect to.
/// It's the main unit of computing resources in AlloyDB.
public struct Instance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The name of the instance resource with the format:
  ///  * projects/{project}/locations/{region}/clusters/{cluster_id}/instances/{instance_id}
  /// where the cluster and instance ID segments should satisfy the regex
  /// expression `[a-z]([a-z0-9-]{0,61}[a-z0-9])?`, e.g. 1-63 characters of
  /// lowercase letters, numbers, and dashes, starting with a letter, and ending
  /// with a letter or number. For more details see https://google.aip.dev/122.
  /// The prefix of the instance resource name is the name of the parent
  /// resource:
  ///  * projects/{project}/locations/{region}/clusters/{cluster_id}
  public var name: Swift.String = Swift.String()

  /// User-settable and human-readable display name for the Instance.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The system-generated UID of the resource. The UID is assigned
  /// when the resource is created, and it is retained until it is deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. Create time stamp
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Update time stamp
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Delete time stamp
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The current serving state of the instance.
  public var state: Instance.State = Instance.State()

  /// Required. The type of the instance. Specified at creation time.
  public var instanceType: Instance.InstanceType = Instance.InstanceType()

  /// Configurations for the machines that host the underlying
  /// database engine.
  public var machineConfig: Instance.MachineConfig? = nil

  /// Availability type of an Instance.
  /// If empty, defaults to REGIONAL for primary instances.
  /// For read pools, availability_type is always UNSPECIFIED. Instances in the
  /// read pools are evenly distributed across available zones within the region
  /// (i.e. read pools with more than one node will have a node in at
  /// least two zones).
  public var availabilityType: Instance.AvailabilityType = Instance.AvailabilityType()

  /// The Compute Engine zone that the instance should serve from, per
  /// https://cloud.google.com/compute/docs/regions-zones
  /// This can ONLY be specified for ZONAL instances.
  /// If present for a REGIONAL instance, an error will be thrown.
  /// If this is absent for a ZONAL instance, instance is created in a random
  /// zone with available capacity.
  public var gceZone: Swift.String = Swift.String()

  /// Database flags. Set at the instance level.
  /// They are copied from the primary instance on secondary instance creation.
  /// Flags that have restrictions default to the value at primary
  /// instance on read instances during creation. Read instances can set new
  /// flags or override existing flags that are relevant for reads, for example,
  /// for enabling columnar cache on a read instance. Flags set on read instance
  /// might or might not be present on the primary instance.
  ///
  ///
  /// This is a list of "key": "value" pairs.
  /// "key": The name of the flag. These flags are passed at instance setup time,
  /// so include both server options and system variables for Postgres. Flags are
  /// specified with underscores, not hyphens.
  /// "value": The value of the flag. Booleans are set to **on** for true
  /// and **off** for false. This field must be omitted if the flag
  /// doesn't take a value.
  public var databaseFlags: [Swift.String: Swift.String] = [:]

  /// Output only. This is set for the read-write VM of the PRIMARY instance
  /// only.
  public var writableNode: Instance.Node? = nil

  /// Output only. List of available read-only VMs in this instance, including
  /// the standby for a PRIMARY instance.
  public var nodes: [Instance.Node] = []

  /// Configuration for query insights.
  public var queryInsightsConfig: Instance.QueryInsightsInstanceConfig? = nil

  /// Configuration for observability.
  public var observabilityConfig: Instance.ObservabilityInstanceConfig? = nil

  /// Read pool instance configuration.
  /// This is required if the value of instanceType is READ_POOL.
  public var readPoolConfig: Instance.ReadPoolConfig? = nil

  /// Output only. The IP address for the Instance.
  /// This is the connection endpoint for an end-user application.
  public var ipAddress: Swift.String = Swift.String()

  /// Output only. The public IP addresses for the Instance. This is available
  /// ONLY when enable_public_ip is set. This is the connection endpoint for an
  /// end-user application.
  public var publicIpAddress: Swift.String = Swift.String()

  /// Output only. Reconciling (https://google.aip.dev/128#reconciliation).
  /// Set to true if the current state of Instance does not match the user's
  /// intended state, and the service is actively updating the resource to
  /// reconcile them. This can happen due to user-triggered updates or
  /// system actions like failover or maintenance.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// For Resource freshness validation (https://google.aip.dev/154)
  public var etag: Swift.String = Swift.String()

  /// Annotations to allow client tools to store small amount of arbitrary data.
  /// This is distinct from labels.
  /// https://google.aip.dev/128
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Client connection specific configurations
  public var clientConnectionConfig: Instance.ClientConnectionConfig? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Optional. The configuration for Private Service Connect (PSC) for the
  /// instance.
  public var pscInstanceConfig: Instance.PscInstanceConfig? = nil

  /// Optional. Instance-level network configuration.
  public var networkConfig: Instance.InstanceNetworkConfig? = nil

  /// Output only. All outbound public IP addresses configured for the instance.
  public var outboundPublicIpAddresses: [Swift.String] = []

  /// Optional. Specifies whether an instance needs to spin up. Once the instance
  /// is active, the activation policy can be updated to the `NEVER` to stop the
  /// instance. Likewise, the activation policy can be updated to `ALWAYS` to
  /// start the instance.
  /// There are restrictions around when an instance can/cannot be activated (for
  /// example, a read pool instance should be stopped before stopping primary
  /// etc.). Please refer to the API documentation for more details.
  public var activationPolicy: Instance.ActivationPolicy = Instance.ActivationPolicy()

  /// Optional. The configuration for Managed Connection Pool (MCP).
  public var connectionPoolConfig: Instance.ConnectionPoolConfig? = nil

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// MachineConfig describes the configuration of a machine.
  public struct MachineConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The number of CPU's in the VM instance.
    public var cpuCount: Swift.Int32 = Swift.Int32()

    /// Machine type of the VM instance. E.g. "n2-highmem-4",
    /// "n2-highmem-8", "c4a-highmem-4-lssd".
    /// cpu_count must match the number of vCPUs in the machine type.
    public var machineType: Swift.String = Swift.String()

    /// Initialize a new instance of `MachineConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MachineConfig().with { $0.cpuCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.MachineConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Details of a single node in the instance.
  /// Nodes in an AlloyDB instance are ephemeral, they can change during
  /// update, failover, autohealing and resize operations.
  public struct Node: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The Compute Engine zone of the VM e.g. "us-central1-b".
    public var zoneId: Swift.String = Swift.String()

    /// Output only. The identifier of the VM e.g.
    /// "test-read-0601-407e52be-ms3l".
    public var id: Swift.String = Swift.String()

    /// Output only. The private IP address of the VM e.g. "10.57.0.34".
    public var ip: Swift.String = Swift.String()

    /// Output only. Determined by state of the compute VM and postgres-service
    /// health. Compute VM state can have values listed in
    /// https://cloud.google.com/compute/docs/instances/instance-life-cycle and
    /// postgres-service health can have values: HEALTHY and UNHEALTHY.
    public var state: Swift.String = Swift.String()

    /// Initialize a new instance of `Node`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Node().with { $0.zoneId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.Node"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// QueryInsights Instance specific configuration.
  public struct QueryInsightsInstanceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Record application tags for an instance.
    /// This flag is turned "on" by default.
    public var recordApplicationTags: Swift.Bool? = nil

    /// Record client address for an instance. Client address is PII information.
    /// This flag is turned "on" by default.
    public var recordClientAddress: Swift.Bool? = nil

    /// Query string length. The default value is 1024.
    /// Any integer between 256 and 4500 is considered valid.
    public var queryStringLength: Swift.UInt32 = Swift.UInt32()

    /// Number of query execution plans captured by Insights per minute
    /// for all queries combined. The default value is 5.
    /// Any integer between 0 and 20 is considered valid.
    public var queryPlansPerMinute: Swift.UInt32? = nil

    /// Initialize a new instance of `QueryInsightsInstanceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QueryInsightsInstanceConfig().with { $0.recordApplicationTags = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.QueryInsightsInstanceConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Observability Instance specific configuration.
  public struct ObservabilityInstanceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Observability feature status for an instance.
    /// This flag is turned "off" by default.
    public var enabled: Swift.Bool? = nil

    /// Preserve comments in query string for an instance.
    /// This flag is turned "off" by default.
    public var preserveComments: Swift.Bool? = nil

    /// Track wait events during query execution for an instance.
    /// This flag is turned "on" by default but tracking is enabled only after
    /// observability enabled flag is also turned on.
    public var trackWaitEvents: Swift.Bool? = nil

    /// Output only. Track wait event types during query execution for an
    /// instance. This flag is turned "on" by default but tracking is enabled
    /// only after observability enabled flag is also turned on. This is
    /// read-only flag and only modifiable by internal API.
    public var trackWaitEventTypes: Swift.Bool? = nil

    /// Query string length. The default value is 10k.
    public var maxQueryStringLength: Swift.Int32? = nil

    /// Record application tags for an instance.
    /// This flag is turned "off" by default.
    public var recordApplicationTags: Swift.Bool? = nil

    /// Number of query execution plans captured by Insights per minute
    /// for all queries combined. The default value is 200.
    /// Any integer between 0 to 200 is considered valid.
    public var queryPlansPerMinute: Swift.Int32? = nil

    /// Track actively running queries on the instance.
    /// If not set, this flag is "off" by default.
    public var trackActiveQueries: Swift.Bool? = nil

    /// Initialize a new instance of `ObservabilityInstanceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ObservabilityInstanceConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.ObservabilityInstanceConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Configuration for a read pool instance.
  public struct ReadPoolConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Read capacity, i.e. number of nodes in a read pool instance.
    public var nodeCount: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `ReadPoolConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReadPoolConfig().with { $0.nodeCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.ReadPoolConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Client connection configuration
  public struct ClientConnectionConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Configuration to enforce connectors only (ex: AuthProxy)
    /// connections to the database.
    public var requireConnectors: Swift.Bool = Swift.Bool()

    /// Optional. SSL configuration option for this instance.
    public var sslConfig: SslConfig? = nil

    /// Initialize a new instance of `ClientConnectionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClientConnectionConfig().with { $0.requireConnectors = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.ClientConnectionConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Configuration for setting up a PSC interface to enable outbound
  /// connectivity.
  public struct PscInterfaceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The network attachment resource created in the consumer network to which
    /// the PSC interface will be linked. This is of the format:
    /// "projects/${CONSUMER_PROJECT}/regions/${REGION}/networkAttachments/${NETWORK_ATTACHMENT_NAME}".
    /// The network attachment must be in the same region as the instance.
    public var networkAttachmentResource: Swift.String = Swift.String()

    /// Initialize a new instance of `PscInterfaceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscInterfaceConfig().with { $0.networkAttachmentResource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.PscInterfaceConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Configuration for setting up PSC service automation. Consumer projects in
  /// the configs will be allowlisted automatically for the instance.
  public struct PscAutoConnectionConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The consumer project to which the PSC service automation endpoint will
    /// be created.
    public var consumerProject: Swift.String = Swift.String()

    /// The consumer network for the PSC service automation, example:
    /// "projects/vpc-host-project/global/networks/default".
    /// The consumer network might be hosted a different project than the
    /// consumer project.
    public var consumerNetwork: Swift.String = Swift.String()

    /// Output only. The IP address of the PSC service automation endpoint.
    public var ipAddress: Swift.String = Swift.String()

    /// Output only. The status of the PSC service automation connection.
    /// Possible values:
    ///   "STATE_UNSPECIFIED" - An invalid state as the default case.
    ///   "ACTIVE" - The connection has been created successfully.
    ///   "FAILED" - The connection is not functional since some resources on the
    /// connection fail to be created.
    ///   "CREATING" - The connection is being created.
    ///   "DELETING" - The connection is being deleted.
    ///   "CREATE_REPAIRING" - The connection is being repaired to complete
    /// creation.
    ///   "DELETE_REPAIRING" - The connection is being repaired to complete
    /// deletion.
    public var status: Swift.String = Swift.String()

    /// Output only. The status of the service connection policy.
    /// Possible values:
    ///   "STATE_UNSPECIFIED" - Default state, when Connection Map is created
    /// initially.
    ///   "VALID" - Set when policy and map configuration is valid, and their
    /// matching can lead to allowing creation of PSC Connections subject to
    /// other constraints like connections limit.
    ///   "CONNECTION_POLICY_MISSING" - No Service Connection Policy found for
    /// this network and Service Class
    ///   "POLICY_LIMIT_REACHED" - Service Connection Policy limit reached for
    ///   this network and Service Class
    ///   "CONSUMER_INSTANCE_PROJECT_NOT_ALLOWLISTED" - The consumer instance
    /// project is not in AllowedGoogleProducersResourceHierarchyLevels of the
    /// matching ServiceConnectionPolicy.
    public var consumerNetworkStatus: Swift.String = Swift.String()

    /// Initialize a new instance of `PscAutoConnectionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscAutoConnectionConfig().with { $0.consumerProject = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.PscAutoConnectionConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// PscInstanceConfig contains PSC related configuration at an
  /// instance level.
  public struct PscInstanceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The service attachment created when Private
    /// Service Connect (PSC) is enabled for the instance.
    /// The name of the resource will be in the format of
    /// `projects/<alloydb-tenant-project-number>/regions/<region-name>/serviceAttachments/<service-attachment-name>`
    public var serviceAttachmentLink: Swift.String = Swift.String()

    /// Optional. List of consumer projects that are allowed to create
    /// PSC endpoints to service-attachments to this instance.
    public var allowedConsumerProjects: [Swift.String] = []

    /// Output only. The DNS name of the instance for PSC connectivity.
    /// Name convention: <uid>.<uid>.<region>.alloydb-psc.goog
    public var pscDnsName: Swift.String = Swift.String()

    /// Optional. Configurations for setting up PSC interfaces attached to the
    /// instance which are used for outbound connectivity. Only primary instances
    /// can have PSC interface attached. Currently we only support 0 or 1 PSC
    /// interface.
    public var pscInterfaceConfigs: [Instance.PscInterfaceConfig] = []

    /// Optional. Configurations for setting up PSC service automation.
    public var pscAutoConnections: [Instance.PscAutoConnectionConfig] = []

    /// Initialize a new instance of `PscInstanceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscInstanceConfig().with { $0.serviceAttachmentLink = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.PscInstanceConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Metadata related to instance-level network configuration.
  public struct InstanceNetworkConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. A list of external network authorized to access this instance.
    public var authorizedExternalNetworks: [Instance.InstanceNetworkConfig.AuthorizedNetwork] = []

    /// Optional. Enabling public ip for the instance.
    public var enablePublicIp: Swift.Bool = Swift.Bool()

    /// Optional. Enabling an outbound public IP address to support a database
    /// server sending requests out into the internet.
    public var enableOutboundPublicIp: Swift.Bool = Swift.Bool()

    /// Output only. The resource link for the VPC network in which instance
    /// resources are created and from which they are accessible via Private IP.
    /// This will be the same value as the parent cluster's network. It is
    /// specified in the form: //
    /// `projects/{project_number}/global/networks/{network_id}`.
    public var network: Swift.String = Swift.String()

    /// Optional. Name of the allocated IP range for the private IP AlloyDB
    /// instance, for example: "google-managed-services-default". If set, the
    /// instance IPs will be created from this allocated range and will override
    /// the IP range used by the parent cluster. The range name must comply with
    /// [RFC 1035](http://datatracker.ietf.org/doc/html/rfc1035). Specifically,
    /// the name must be 1-63 characters long and match the regular expression
    /// [a-z]([-a-z0-9]*[a-z0-9])?.
    public var allocatedIpRangeOverride: Swift.String = Swift.String()

    /// Initialize a new instance of `InstanceNetworkConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceNetworkConfig().with { $0.authorizedExternalNetworks = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// AuthorizedNetwork contains metadata for an authorized network.
    public struct AuthorizedNetwork: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// CIDR range for one authorzied network of the instance.
      public var cidrRange: Swift.String = Swift.String()

      /// Initialize a new instance of `AuthorizedNetwork`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = AuthorizedNetwork().with { $0.cidrRange = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return
          "type.googleapis.com/google.cloud.alloydb.v1.Instance.InstanceNetworkConfig.AuthorizedNetwork"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.InstanceNetworkConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Configuration for Managed Connection Pool (MCP).
  public struct ConnectionPoolConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Whether to enable Managed Connection Pool (MCP).
    public var enabled: Swift.Bool = Swift.Bool()

    /// Optional. Connection Pool flags, as a list of "key": "value" pairs.
    public var flags: [Swift.String: Swift.String] = [:]

    /// Output only. The number of running poolers per instance.
    public var poolerCount: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `ConnectionPoolConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConnectionPoolConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.Instance.ConnectionPoolConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Instance State
  public enum State: Codable, Equatable, Sendable {
    /// The state of the instance is unknown.
    case unspecified
    /// The instance is active and running.
    case ready
    /// The instance is stopped. Instance name and IP resources are preserved.
    case stopped
    /// The instance is being created.
    case creating
    /// The instance is being deleted.
    case deleting
    /// The instance is down for maintenance.
    case maintenance
    /// The creation of the instance failed or a fatal error occurred during
    /// an operation on the instance.
    /// Note: Instances in this state would tried to be auto-repaired. And
    /// Customers should be able to restart, update or delete these instances.
    case failed
    /// Index 7 is used in the producer apis for ROLLED_BACK state. Keeping that
    /// index unused in case that state also needs to exposed via consumer apis
    /// in future.
    /// The instance has been configured to sync data from some other source.
    case bootstrapping
    /// The instance is being promoted.
    case promoting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ready: return 1
      case .stopped: return 2
      case .creating: return 3
      case .deleting: return 4
      case .maintenance: return 5
      case .failed: return 6
      case .bootstrapping: return 8
      case .promoting: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .ready: return "READY"
      case .stopped: return "STOPPED"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .maintenance: return "MAINTENANCE"
      case .failed: return "FAILED"
      case .bootstrapping: return "BOOTSTRAPPING"
      case .promoting: return "PROMOTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "READY": self = .ready
      case "STOPPED": self = .stopped
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "MAINTENANCE": self = .maintenance
      case "FAILED": self = .failed
      case "BOOTSTRAPPING": self = .bootstrapping
      case "PROMOTING": self = .promoting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ready
      case 2: self = .stopped
      case 3: self = .creating
      case 4: self = .deleting
      case 5: self = .maintenance
      case 6: self = .failed
      case 8: self = .bootstrapping
      case 9: self = .promoting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ready: return try container.encode(1)
      case .stopped: return try container.encode(2)
      case .creating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .maintenance: return try container.encode(5)
      case .failed: return try container.encode(6)
      case .bootstrapping: return try container.encode(8)
      case .promoting: return try container.encode(9)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of an Instance
  public enum InstanceType: Codable, Equatable, Sendable {
    /// The type of the instance is unknown.
    case unspecified
    /// PRIMARY instances support read and write operations.
    case primary
    /// READ POOL instances support read operations only. Each read pool instance
    /// consists of one or more homogeneous nodes.
    ///  * Read pool of size 1 can only have zonal availability.
    ///  * Read pools with node count of 2 or more can have regional
    ///    availability (nodes are present in 2 or more zones in a region).
    case readPool
    /// SECONDARY instances support read operations only. SECONDARY instance
    /// is a cross-region read replica
    case secondary
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .primary: return 1
      case .readPool: return 2
      case .secondary: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "INSTANCE_TYPE_UNSPECIFIED"
      case .primary: return "PRIMARY"
      case .readPool: return "READ_POOL"
      case .secondary: return "SECONDARY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "INSTANCE_TYPE_UNSPECIFIED": self = .unspecified
      case "PRIMARY": self = .primary
      case "READ_POOL": self = .readPool
      case "SECONDARY": self = .secondary
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .primary
      case 2: self = .readPool
      case 3: self = .secondary
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .primary: return try container.encode(1)
      case .readPool: return try container.encode(2)
      case .secondary: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The Availability type of an instance. Potential values:
  ///
  /// - ZONAL: The instance serves data from only one zone. Outages in that
  ///     zone affect instance availability.
  /// - REGIONAL: The instance can serve data from more than one zone in a
  ///     region (it is highly available).
  public enum AvailabilityType: Codable, Equatable, Sendable {
    /// This is an unknown Availability type.
    case unspecified
    /// Zonal available instance.
    case zonal
    /// Regional (or Highly) available instance.
    case regional
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .zonal: return 1
      case .regional: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "AVAILABILITY_TYPE_UNSPECIFIED"
      case .zonal: return "ZONAL"
      case .regional: return "REGIONAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "AVAILABILITY_TYPE_UNSPECIFIED": self = .unspecified
      case "ZONAL": self = .zonal
      case "REGIONAL": self = .regional
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .zonal
      case 2: self = .regional
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .zonal: return try container.encode(1)
      case .regional: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Specifies whether an instance needs to spin up.
  public enum ActivationPolicy: Codable, Equatable, Sendable {
    /// The policy is not specified.
    case unspecified
    /// The instance is running.
    case always
    /// The instance is not running.
    case never
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .always: return 1
      case .never: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "ACTIVATION_POLICY_UNSPECIFIED"
      case .always: return "ALWAYS"
      case .never: return "NEVER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "ACTIVATION_POLICY_UNSPECIFIED": self = .unspecified
      case "ALWAYS": self = .always
      case "NEVER": self = .never
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .always
      case 2: self = .never
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .always: return try container.encode(1)
      case .never: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.alloydb.v1.Instance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
