// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message for ListDatabases request.
public struct ListDatabasesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Parent value for ListDatabasesRequest.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of databases to return. The service may return
  /// fewer than this value. If unspecified, 2000 is the default page_size. The
  /// max value of page_size will be 4000, values above max will be coerced to
  /// max.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous `ListDatabases` call.
  /// This should be provided to retrieve the subsequent page.
  /// This field is currently not supported, its value will be ignored if passed.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Filtering results.
  /// This field is currently not supported, its value will be ignored if passed.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListDatabasesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListDatabasesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.ListDatabasesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
