// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleType
@_spi(GoogleCloudInternal) import GoogleWKT

/// MaintenanceUpdatePolicy defines the policy for system updates.
public struct MaintenanceUpdatePolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Preferred windows to perform maintenance. Currently limited to 1.
  public var maintenanceWindows: [MaintenanceUpdatePolicy.MaintenanceWindow] = []

  /// Periods to deny maintenance. Currently limited to 1.
  public var denyMaintenancePeriods: [MaintenanceUpdatePolicy.DenyMaintenancePeriod] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MaintenanceUpdatePolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MaintenanceUpdatePolicy().with { $0.maintenanceWindows = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let maintenanceWindows = CodingKeys(stringValue: "maintenanceWindows")
    static let denyMaintenancePeriods = CodingKeys(stringValue: "denyMaintenancePeriods")

    static let _knownKeys: Set<Swift.String> = [
      "maintenanceWindows",
      "denyMaintenancePeriods",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [MaintenanceUpdatePolicy.MaintenanceWindow].self, forKey: .maintenanceWindows)
    {
      self.maintenanceWindows = value
    }
    if let value = try container.decodeIfPresent(
      [MaintenanceUpdatePolicy.DenyMaintenancePeriod].self, forKey: .denyMaintenancePeriods)
    {
      self.denyMaintenancePeriods = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.maintenanceWindows, forKey: .maintenanceWindows)
    try container.encode(self.denyMaintenancePeriods, forKey: .denyMaintenancePeriods)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// MaintenanceWindow specifies a preferred day and time for maintenance.
  public struct MaintenanceWindow: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Preferred day of the week for maintenance, e.g. MONDAY, TUESDAY, etc.
    public var day: GoogleType.DayOfWeek = GoogleType.DayOfWeek()

    /// Preferred time to start the maintenance operation on the specified day.
    /// Maintenance will start within 1 hour of this time.
    public var startTime: GoogleType.TimeOfDay? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MaintenanceWindow`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MaintenanceWindow().with { $0.day = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let day = CodingKeys(stringValue: "day")
      static let startTime = CodingKeys(stringValue: "startTime")

      static let _knownKeys: Set<Swift.String> = [
        "day",
        "startTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(GoogleType.DayOfWeek.self, forKey: .day) {
        self.day = value
      }
      self.startTime = try container.decodeIfPresent(GoogleType.TimeOfDay.self, forKey: .startTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.day, forKey: .day)
      try container.encodeIfPresent(self.startTime, forKey: .startTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.MaintenanceUpdatePolicy.MaintenanceWindow"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// DenyMaintenancePeriod definition. Excepting emergencies, maintenance
  /// will not be scheduled to start within this deny period. The start_date must
  /// be less than the end_date.
  public struct DenyMaintenancePeriod: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Deny period start date.
    /// This can be:
    /// * A full date, with non-zero year, month and day values OR
    /// * A month and day value, with a zero year for recurring
    public var startDate: GoogleType.Date? = nil

    /// Deny period end date.
    /// This can be:
    /// * A full date, with non-zero year, month and day values OR
    /// * A month and day value, with a zero year for recurring
    public var endDate: GoogleType.Date? = nil

    /// Time in UTC when the deny period starts on start_date and ends on
    /// end_date. This can be:
    /// * Full time OR
    /// * All zeros for 00:00:00 UTC
    public var time: GoogleType.TimeOfDay? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DenyMaintenancePeriod`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DenyMaintenancePeriod().with { $0.startDate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startDate = CodingKeys(stringValue: "startDate")
      static let endDate = CodingKeys(stringValue: "endDate")
      static let time = CodingKeys(stringValue: "time")

      static let _knownKeys: Set<Swift.String> = [
        "startDate",
        "endDate",
        "time",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.startDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .startDate)
      self.endDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .endDate)
      self.time = try container.decodeIfPresent(GoogleType.TimeOfDay.self, forKey: .time)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.startDate, forKey: .startDate)
      try container.encodeIfPresent(self.endDate, forKey: .endDate)
      try container.encodeIfPresent(self.time, forKey: .time)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.alloydb.v1.MaintenanceUpdatePolicy.DenyMaintenancePeriod"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.MaintenanceUpdatePolicy"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
