// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message for registering Restoring from CloudSQL resource.
public struct RestoreFromCloudSQLRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The location of the new cluster. For the required format, see the
  /// comment on Cluster.name field.
  public var parent: Swift.String = Swift.String()

  /// Required. ID of the requesting object.
  public var clusterId: Swift.String = Swift.String()

  /// Required. The resource being created
  public var cluster: Cluster? = nil

  /// The source CloudSQL resource to restore from.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `RestoreFromCloudSQLRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreFromCloudSQLRequest().with { $0.cloudsqlBackupRunSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case cloudsqlBackupRunSource = "cloudsqlBackupRunSource"
    case parent = "parent"
    case clusterId = "clusterId"
    case cluster = "cluster"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.clusterId = try container.decode(Swift.String.self, forKey: .clusterId)
    self.cluster = try container.decodeIfPresent(Cluster.self, forKey: .cluster)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let cloudsqlBackupRunSource = try container.decodeIfPresent(
      CloudSQLBackupRunSource?.self, forKey: .cloudsqlBackupRunSource)
    {
      try sourceCheckAndSet(.cloudsqlBackupRunSource(cloudsqlBackupRunSource))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.clusterId, forKey: .clusterId)
    try container.encode(self.cluster, forKey: .cluster)

    if let choice = self.source {
      switch choice {
      case .cloudsqlBackupRunSource(let value):
        try container.encode(value, forKey: .cloudsqlBackupRunSource)
      }
    }
  }

  /// The source CloudSQL resource to restore from.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Cluster created from CloudSQL backup run.
    indirect case cloudsqlBackupRunSource(CloudSQLBackupRunSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.RestoreFromCloudSQLRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
