// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message for restoring a Cluster from a backup or another cluster at a given
/// point in time.
/// NEXT_ID: 11
public struct RestoreClusterRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the parent resource. For the required format, see the
  /// comment on the Cluster.name field.
  public var parent: Swift.String = Swift.String()

  /// Required. ID of the requesting object.
  public var clusterId: Swift.String = Swift.String()

  /// Required. The resource being created
  public var cluster: Cluster? = nil

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server ignores the
  /// request if it has already been completed. The server guarantees that for at
  /// least 60 minutes since the first request.
  ///
  /// For example, consider a situation where you make an initial request and
  /// the request times out. If you make the request again with the same request
  /// ID, the server can check if the original operation with the same request ID
  /// was received, and if so, ignores the second request. This prevents
  /// clients from accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Optional. If set, performs request validation, for example, permission
  /// checks and any other type of validation, but does not actually execute the
  /// create request.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Required.
  /// The source to import from.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `RestoreClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreClusterRequest().with { $0.backupSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case backupSource = "backupSource"
    case continuousBackupSource = "continuousBackupSource"
    case parent = "parent"
    case clusterId = "clusterId"
    case cluster = "cluster"
    case requestId = "requestId"
    case validateOnly = "validateOnly"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.clusterId = try container.decode(Swift.String.self, forKey: .clusterId)
    self.cluster = try container.decodeIfPresent(Cluster.self, forKey: .cluster)
    self.requestId = try container.decode(Swift.String.self, forKey: .requestId)
    self.validateOnly = try container.decode(Swift.Bool.self, forKey: .validateOnly)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let backupSource = try container.decodeIfPresent(BackupSource?.self, forKey: .backupSource) {
      try sourceCheckAndSet(.backupSource(backupSource))
    }
    if let continuousBackupSource = try container.decodeIfPresent(
      ContinuousBackupSource?.self, forKey: .continuousBackupSource)
    {
      try sourceCheckAndSet(.continuousBackupSource(continuousBackupSource))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.clusterId, forKey: .clusterId)
    try container.encode(self.cluster, forKey: .cluster)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.validateOnly, forKey: .validateOnly)

    if let choice = self.source {
      switch choice {
      case .backupSource(let value):
        try container.encode(value, forKey: .backupSource)
      case .continuousBackupSource(let value):
        try container.encode(value, forKey: .continuousBackupSource)
      }
    }
  }

  /// Required.
  /// The source to import from.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Backup source.
    indirect case backupSource(BackupSource?)
    /// ContinuousBackup source. Continuous backup needs to be enabled in the
    /// source cluster for this operation to succeed.
    indirect case continuousBackupSource(ContinuousBackupSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.RestoreClusterRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
