// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Message for registering Restoring from CloudSQL resource.
public struct RestoreFromCloudSQLRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The location of the new cluster. For the required format, see the
  /// comment on Cluster.name field.
  public var parent: Swift.String = Swift.String()

  /// Required. ID of the requesting object.
  public var clusterId: Swift.String = Swift.String()

  /// Required. The resource being created
  public var cluster: Cluster? = nil

  /// The source CloudSQL resource to restore from.
  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RestoreFromCloudSQLRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreFromCloudSQLRequest().with { $0.cloudsqlBackupRunSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cloudsqlBackupRunSource = CodingKeys(stringValue: "cloudsqlBackupRunSource")
    static let parent = CodingKeys(stringValue: "parent")
    static let clusterId = CodingKeys(stringValue: "clusterId")
    static let cluster = CodingKeys(stringValue: "cluster")

    static let _knownKeys: Set<Swift.String> = [
      "cloudsqlBackupRunSource",
      "parent",
      "clusterId",
      "cluster",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterId) {
      self.clusterId = value
    }
    self.cluster = try container.decodeIfPresent(Cluster.self, forKey: .cluster)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let cloudsqlBackupRunSource = try container.decodeIfPresent(
      CloudSQLBackupRunSource?.self, forKey: .cloudsqlBackupRunSource)
    {
      try sourceCheckAndSet(.cloudsqlBackupRunSource(cloudsqlBackupRunSource))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.clusterId, forKey: .clusterId)
    try container.encodeIfPresent(self.cluster, forKey: .cluster)

    if let choice = self.source {
      switch choice {
      case .cloudsqlBackupRunSource(let value):
        try container.encode(value, forKey: .cloudsqlBackupRunSource)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The source CloudSQL resource to restore from.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Cluster created from CloudSQL backup run.
    indirect case cloudsqlBackupRunSource(CloudSQLBackupRunSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.RestoreFromCloudSQLRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
