// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// UpgradeClusterResponse contains the response for upgrade cluster operation.
public struct UpgradeClusterResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Status of upgrade operation.
  public var status: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

  /// A user friendly message summarising the upgrade operation details and the
  /// next steps for the user if there is any.
  public var message: Swift.String = Swift.String()

  /// Array of upgrade details for the current cluster and all the secondary
  /// clusters associated with this cluster.
  public var clusterUpgradeDetails: [UpgradeClusterResponse.ClusterUpgradeDetails] = []

  /// Initialize a new instance of `UpgradeClusterResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpgradeClusterResponse().with { $0.status = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Stage information for different stages in the upgrade process.
  public struct StageInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The stage.
    public var stage: UpgradeClusterResponse.Stage = UpgradeClusterResponse.Stage()

    /// Status of the stage.
    public var status: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

    /// logs_url is the URL for the logs associated with a stage if that stage
    /// has logs. Right now, only three stages have logs: ALLOYDB_PRECHECK,
    /// PG_UPGRADE_CHECK, PRIMARY_INSTANCE_UPGRADE.
    public var logsUrl: Swift.String = Swift.String()

    /// Initialize a new instance of `StageInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StageInfo().with { $0.stage = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterResponse.StageInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Details regarding the upgrade of instances associated with a cluster.
  public struct InstanceUpgradeDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Normalized name of the instance.
    public var name: Swift.String = Swift.String()

    /// Upgrade status of the instance.
    public var upgradeStatus: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

    /// Instance type.
    public var instanceType: Instance.InstanceType = Instance.InstanceType()

    /// Initialize a new instance of `InstanceUpgradeDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceUpgradeDetails().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return
        "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterResponse.InstanceUpgradeDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Upgrade details of a cluster. This cluster can be primary or secondary.
  public struct ClusterUpgradeDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Normalized name of the cluster
    public var name: Swift.String = Swift.String()

    /// Upgrade status of the cluster.
    public var upgradeStatus: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

    /// Cluster type which can either be primary or secondary.
    public var clusterType: Cluster.ClusterType = Cluster.ClusterType()

    /// Database version of the cluster after the upgrade operation. This will be
    /// the target version if the upgrade was successful otherwise it remains the
    /// same as that before the upgrade operation.
    public var databaseVersion: DatabaseVersion = DatabaseVersion()

    /// Array containing stage info associated with this cluster.
    public var stageInfo: [UpgradeClusterResponse.StageInfo] = []

    /// Upgrade details of the instances directly associated with this cluster.
    public var instanceUpgradeDetails: [UpgradeClusterResponse.InstanceUpgradeDetails] = []

    /// Initialize a new instance of `ClusterUpgradeDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClusterUpgradeDetails().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return
        "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterResponse.ClusterUpgradeDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Status of upgrade operation.
  public enum Status: Codable, Equatable, Sendable {
    /// Unspecified status.
    case unspecified
    /// Operation succeeded.
    case success
    /// Operation failed.
    case failed
    /// Operation partially succeeded.
    case partialSuccess
    /// Not started.
    case notStarted
    /// In progress.
    case inProgress
    /// Cancel is in progress.
    case cancelInProgress
    /// Cancellation complete.
    case cancelled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .success: return 1
      case .failed: return 2
      case .partialSuccess: return 3
      case .notStarted: return 4
      case .inProgress: return 5
      case .cancelInProgress: return 6
      case .cancelled: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .success: return "SUCCESS"
      case .failed: return "FAILED"
      case .partialSuccess: return "PARTIAL_SUCCESS"
      case .notStarted: return "NOT_STARTED"
      case .inProgress: return "IN_PROGRESS"
      case .cancelInProgress: return "CANCEL_IN_PROGRESS"
      case .cancelled: return "CANCELLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "NOT_STARTED": self = .notStarted
      case "IN_PROGRESS": self = .inProgress
      case "SUCCESS": self = .success
      case "FAILED": self = .failed
      case "PARTIAL_SUCCESS": self = .partialSuccess
      case "CANCEL_IN_PROGRESS": self = .cancelInProgress
      case "CANCELLED": self = .cancelled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 4: self = .notStarted
      case 5: self = .inProgress
      case 1: self = .success
      case 2: self = .failed
      case 3: self = .partialSuccess
      case 6: self = .cancelInProgress
      case 7: self = .cancelled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .success: return try container.encode(1)
      case .failed: return try container.encode(2)
      case .partialSuccess: return try container.encode(3)
      case .notStarted: return try container.encode(4)
      case .inProgress: return try container.encode(5)
      case .cancelInProgress: return try container.encode(6)
      case .cancelled: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Stage in the upgrade.
  public enum Stage: Codable, Equatable, Sendable {
    /// Unspecified stage.
    case unspecified
    /// Pre-upgrade custom checks, not covered by pg_upgrade.
    case alloydbPrecheck
    /// Pre-upgrade pg_upgrade checks.
    case pgUpgradeCheck
    /// Upgrade the primary instance(downtime).
    case primaryInstanceUpgrade
    /// This stage is read pool upgrade.
    case readPoolInstancesUpgrade
    /// Clone the original cluster.
    case prepareForUpgrade
    /// Rollback in case of critical failures.
    case rollback
    /// Cleanup.
    case cleanup
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .alloydbPrecheck: return 1
      case .pgUpgradeCheck: return 2
      case .primaryInstanceUpgrade: return 3
      case .readPoolInstancesUpgrade: return 4
      case .prepareForUpgrade: return 5
      case .rollback: return 6
      case .cleanup: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STAGE_UNSPECIFIED"
      case .alloydbPrecheck: return "ALLOYDB_PRECHECK"
      case .pgUpgradeCheck: return "PG_UPGRADE_CHECK"
      case .primaryInstanceUpgrade: return "PRIMARY_INSTANCE_UPGRADE"
      case .readPoolInstancesUpgrade: return "READ_POOL_INSTANCES_UPGRADE"
      case .prepareForUpgrade: return "PREPARE_FOR_UPGRADE"
      case .rollback: return "ROLLBACK"
      case .cleanup: return "CLEANUP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STAGE_UNSPECIFIED": self = .unspecified
      case "ALLOYDB_PRECHECK": self = .alloydbPrecheck
      case "PG_UPGRADE_CHECK": self = .pgUpgradeCheck
      case "PREPARE_FOR_UPGRADE": self = .prepareForUpgrade
      case "PRIMARY_INSTANCE_UPGRADE": self = .primaryInstanceUpgrade
      case "READ_POOL_INSTANCES_UPGRADE": self = .readPoolInstancesUpgrade
      case "ROLLBACK": self = .rollback
      case "CLEANUP": self = .cleanup
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .alloydbPrecheck
      case 2: self = .pgUpgradeCheck
      case 5: self = .prepareForUpgrade
      case 3: self = .primaryInstanceUpgrade
      case 4: self = .readPoolInstancesUpgrade
      case 6: self = .rollback
      case 7: self = .cleanup
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .alloydbPrecheck: return try container.encode(1)
      case .pgUpgradeCheck: return try container.encode(2)
      case .primaryInstanceUpgrade: return try container.encode(3)
      case .readPoolInstancesUpgrade: return try container.encode(4)
      case .prepareForUpgrade: return try container.encode(5)
      case .rollback: return try container.encode(6)
      case .cleanup: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
