// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message for current status of the Major Version Upgrade operation.
public struct UpgradeClusterStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Cluster Major Version Upgrade state.
  public var state: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

  /// Whether the operation is cancellable.
  public var cancellable: Swift.Bool = Swift.Bool()

  /// Source database major version.
  public var sourceVersion: DatabaseVersion = DatabaseVersion()

  /// Target database major version.
  public var targetVersion: DatabaseVersion = DatabaseVersion()

  /// Status of all upgrade stages.
  public var stages: [UpgradeClusterStatus.StageStatus] = []

  /// Initialize a new instance of `UpgradeClusterStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpgradeClusterStatus().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Status of an upgrade stage.
  public struct StageStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Upgrade stage.
    public var stage: UpgradeClusterResponse.Stage = UpgradeClusterResponse.Stage()

    /// State of this stage.
    public var state: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

    /// Output only. Timing information for the stage execution.
    public var schedule: UpgradeClusterStatus.StageStatus.StageSchedule? = nil

    /// Stage specific status information, if any.
    public var stageSpecificStatus: OneOf_StageSpecificStatus? = nil

    /// Initialize a new instance of `StageStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StageStatus().with { $0.readPoolInstancesUpgrade = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case readPoolInstancesUpgrade = "readPoolInstancesUpgrade"
      case stage = "stage"
      case state = "state"
      case schedule = "schedule"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.stage = try container.decode(UpgradeClusterResponse.Stage.self, forKey: .stage)
      self.state = try container.decode(UpgradeClusterResponse.Status.self, forKey: .state)
      self.schedule = try container.decodeIfPresent(
        UpgradeClusterStatus.StageStatus.StageSchedule.self, forKey: .schedule)

      var stageSpecificStatus: OneOf_StageSpecificStatus? = nil
      let stageSpecificStatusCheckAndSet = {
        if stageSpecificStatus != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'stageSpecificStatus'"))
        }
        stageSpecificStatus = $0
      }
      if let readPoolInstancesUpgrade = try container.decodeIfPresent(
        UpgradeClusterStatus.ReadPoolInstancesUpgradeStageStatus?.self,
        forKey: .readPoolInstancesUpgrade)
      {
        try stageSpecificStatusCheckAndSet(.readPoolInstancesUpgrade(readPoolInstancesUpgrade))
      }
      self.stageSpecificStatus = stageSpecificStatus
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.stage, forKey: .stage)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.schedule, forKey: .schedule)

      if let choice = self.stageSpecificStatus {
        switch choice {
        case .readPoolInstancesUpgrade(let value):
          try container.encode(value, forKey: .readPoolInstancesUpgrade)
        }
      }
    }

    /// Timing information for the stage execution.
    public struct StageSchedule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// When the stage is expected to start. Set only if the stage has not
      /// started yet.
      public var estimatedStartTime: GoogleCloudWkt.Timestamp? = nil

      /// Actual start time of the stage. Set only if the stage has started.
      public var actualStartTime: GoogleCloudWkt.Timestamp? = nil

      /// When the stage is expected to end. Set only if the stage has not
      /// completed yet.
      public var estimatedEndTime: GoogleCloudWkt.Timestamp? = nil

      /// Actual end time of the stage. Set only if the stage has completed.
      public var actualEndTime: GoogleCloudWkt.Timestamp? = nil

      /// Initialize a new instance of `StageSchedule`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = StageSchedule().with { $0.estimatedStartTime = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return
          "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterStatus.StageStatus.StageSchedule"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Stage specific status information, if any.
    public enum OneOf_StageSpecificStatus: Codable, Equatable, Sendable {
      /// Read pool instances upgrade metadata.
      indirect case readPoolInstancesUpgrade(
        UpgradeClusterStatus.ReadPoolInstancesUpgradeStageStatus?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterStatus.StageStatus"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Read pool instances upgrade specific status.
  public struct ReadPoolInstancesUpgradeStageStatus: Codable, Equatable, GoogleCloudWkt
      ._AnyPackable,
    Sendable
  {
    /// Read pool instances upgrade statistics.
    public var upgradeStats: UpgradeClusterStatus.ReadPoolInstancesUpgradeStageStatus.Stats? = nil

    /// Initialize a new instance of `ReadPoolInstancesUpgradeStageStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReadPoolInstancesUpgradeStageStatus().with { $0.upgradeStats = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Upgrade stats for read pool instances.
    public struct Stats: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Number of read pool instances for which upgrade has not started.
      public var notStarted: Swift.Int32 = Swift.Int32()

      /// Number of read pool instances undergoing upgrade.
      public var ongoing: Swift.Int32 = Swift.Int32()

      /// Number of read pool instances successfully upgraded.
      public var success: Swift.Int32 = Swift.Int32()

      /// Number of read pool instances which failed to upgrade.
      public var failed: Swift.Int32 = Swift.Int32()

      /// Initialize a new instance of `Stats`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Stats().with { $0.notStarted = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return
          "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterStatus.ReadPoolInstancesUpgradeStageStatus.Stats"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return
        "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterStatus.ReadPoolInstancesUpgradeStageStatus"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterStatus"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
