// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Upgrades a cluster.
public struct UpgradeClusterRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the cluster.
  public var name: Swift.String = Swift.String()

  /// Required. The version the cluster is going to be upgraded to.
  public var version: DatabaseVersion = DatabaseVersion()

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server ignores the
  /// request if it has already been completed. The server guarantees that for at
  /// least 60 minutes since the first request.
  ///
  /// For example, consider a situation where you make an initial request and
  /// the request times out. If you make the request again with the same request
  /// ID, the server can check if the original operation with the same request ID
  /// was received, and if so, ignores the second request. This prevents
  /// clients from accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Optional. If set, performs request validation, for example, permission
  /// checks and any other type of validation, but does not actually execute the
  /// create request.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Optional. The current etag of the Cluster.
  /// If an etag is provided and does not match the current etag of the Cluster,
  /// upgrade will be blocked and an ABORTED error will be returned.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `UpgradeClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpgradeClusterRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
