// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// UpgradeClusterResponse contains the response for upgrade cluster operation.
public struct UpgradeClusterResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Status of upgrade operation.
  public var status: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

  /// A user friendly message summarising the upgrade operation details and the
  /// next steps for the user if there is any.
  public var message: Swift.String = Swift.String()

  /// Array of upgrade details for the current cluster and all the secondary
  /// clusters associated with this cluster.
  public var clusterUpgradeDetails: [UpgradeClusterResponse.ClusterUpgradeDetails] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpgradeClusterResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpgradeClusterResponse().with { $0.status = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let status = CodingKeys(stringValue: "status")
    static let message = CodingKeys(stringValue: "message")
    static let clusterUpgradeDetails = CodingKeys(stringValue: "clusterUpgradeDetails")

    static let _knownKeys: Set<Swift.String> = [
      "status",
      "message",
      "clusterUpgradeDetails",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      UpgradeClusterResponse.Status.self, forKey: .status)
    {
      self.status = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
      self.message = value
    }
    if let value = try container.decodeIfPresent(
      [UpgradeClusterResponse.ClusterUpgradeDetails].self, forKey: .clusterUpgradeDetails)
    {
      self.clusterUpgradeDetails = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.status, forKey: .status)
    try container.encode(self.message, forKey: .message)
    try container.encode(self.clusterUpgradeDetails, forKey: .clusterUpgradeDetails)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Stage information for different stages in the upgrade process.
  public struct StageInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The stage.
    public var stage: UpgradeClusterResponse.Stage = UpgradeClusterResponse.Stage()

    /// Status of the stage.
    public var status: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

    /// logs_url is the URL for the logs associated with a stage if that stage
    /// has logs. Right now, only three stages have logs: ALLOYDB_PRECHECK,
    /// PG_UPGRADE_CHECK, PRIMARY_INSTANCE_UPGRADE.
    public var logsUrl: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StageInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StageInfo().with { $0.stage = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let stage = CodingKeys(stringValue: "stage")
      static let status = CodingKeys(stringValue: "status")
      static let logsUrl = CodingKeys(stringValue: "logsUrl")

      static let _knownKeys: Set<Swift.String> = [
        "stage",
        "status",
        "logsUrl",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        UpgradeClusterResponse.Stage.self, forKey: .stage)
      {
        self.stage = value
      }
      if let value = try container.decodeIfPresent(
        UpgradeClusterResponse.Status.self, forKey: .status)
      {
        self.status = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logsUrl) {
        self.logsUrl = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.stage, forKey: .stage)
      try container.encode(self.status, forKey: .status)
      try container.encode(self.logsUrl, forKey: .logsUrl)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterResponse.StageInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Details regarding the upgrade of instances associated with a cluster.
  public struct InstanceUpgradeDetails: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Normalized name of the instance.
    public var name: Swift.String = Swift.String()

    /// Upgrade status of the instance.
    public var upgradeStatus: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

    /// Instance type.
    public var instanceType: Instance.InstanceType = Instance.InstanceType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InstanceUpgradeDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceUpgradeDetails().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let upgradeStatus = CodingKeys(stringValue: "upgradeStatus")
      static let instanceType = CodingKeys(stringValue: "instanceType")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "upgradeStatus",
        "instanceType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(
        UpgradeClusterResponse.Status.self, forKey: .upgradeStatus)
      {
        self.upgradeStatus = value
      }
      if let value = try container.decodeIfPresent(
        Instance.InstanceType.self, forKey: .instanceType)
      {
        self.instanceType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.upgradeStatus, forKey: .upgradeStatus)
      try container.encode(self.instanceType, forKey: .instanceType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterResponse.InstanceUpgradeDetails"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Upgrade details of a cluster. This cluster can be primary or secondary.
  public struct ClusterUpgradeDetails: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Normalized name of the cluster
    public var name: Swift.String = Swift.String()

    /// Upgrade status of the cluster.
    public var upgradeStatus: UpgradeClusterResponse.Status = UpgradeClusterResponse.Status()

    /// Cluster type which can either be primary or secondary.
    public var clusterType: Cluster.ClusterType = Cluster.ClusterType()

    /// Database version of the cluster after the upgrade operation. This will be
    /// the target version if the upgrade was successful otherwise it remains the
    /// same as that before the upgrade operation.
    public var databaseVersion: DatabaseVersion = DatabaseVersion()

    /// Array containing stage info associated with this cluster.
    public var stageInfo: [UpgradeClusterResponse.StageInfo] = []

    /// Upgrade details of the instances directly associated with this cluster.
    public var instanceUpgradeDetails: [UpgradeClusterResponse.InstanceUpgradeDetails] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ClusterUpgradeDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClusterUpgradeDetails().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let upgradeStatus = CodingKeys(stringValue: "upgradeStatus")
      static let clusterType = CodingKeys(stringValue: "clusterType")
      static let databaseVersion = CodingKeys(stringValue: "databaseVersion")
      static let stageInfo = CodingKeys(stringValue: "stageInfo")
      static let instanceUpgradeDetails = CodingKeys(stringValue: "instanceUpgradeDetails")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "upgradeStatus",
        "clusterType",
        "databaseVersion",
        "stageInfo",
        "instanceUpgradeDetails",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(
        UpgradeClusterResponse.Status.self, forKey: .upgradeStatus)
      {
        self.upgradeStatus = value
      }
      if let value = try container.decodeIfPresent(Cluster.ClusterType.self, forKey: .clusterType) {
        self.clusterType = value
      }
      if let value = try container.decodeIfPresent(DatabaseVersion.self, forKey: .databaseVersion) {
        self.databaseVersion = value
      }
      if let value = try container.decodeIfPresent(
        [UpgradeClusterResponse.StageInfo].self, forKey: .stageInfo)
      {
        self.stageInfo = value
      }
      if let value = try container.decodeIfPresent(
        [UpgradeClusterResponse.InstanceUpgradeDetails].self, forKey: .instanceUpgradeDetails)
      {
        self.instanceUpgradeDetails = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.upgradeStatus, forKey: .upgradeStatus)
      try container.encode(self.clusterType, forKey: .clusterType)
      try container.encode(self.databaseVersion, forKey: .databaseVersion)
      try container.encode(self.stageInfo, forKey: .stageInfo)
      try container.encode(self.instanceUpgradeDetails, forKey: .instanceUpgradeDetails)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterResponse.ClusterUpgradeDetails"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Status of upgrade operation.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Status: Codable, Equatable, Sendable {
    /// Unspecified status.
    case unspecified
    /// Operation succeeded.
    case success
    /// Operation failed.
    case failed
    /// Operation partially succeeded.
    case partialSuccess
    /// Not started.
    case notStarted
    /// In progress.
    case inProgress
    /// Cancel is in progress.
    case cancelInProgress
    /// Cancellation complete.
    case cancelled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .success: return 1
      case .failed: return 2
      case .partialSuccess: return 3
      case .notStarted: return 4
      case .inProgress: return 5
      case .cancelInProgress: return 6
      case .cancelled: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .success: return "SUCCESS"
      case .failed: return "FAILED"
      case .partialSuccess: return "PARTIAL_SUCCESS"
      case .notStarted: return "NOT_STARTED"
      case .inProgress: return "IN_PROGRESS"
      case .cancelInProgress: return "CANCEL_IN_PROGRESS"
      case .cancelled: return "CANCELLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Status/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "NOT_STARTED": self = .notStarted
      case "IN_PROGRESS": self = .inProgress
      case "SUCCESS": self = .success
      case "FAILED": self = .failed
      case "PARTIAL_SUCCESS": self = .partialSuccess
      case "CANCEL_IN_PROGRESS": self = .cancelInProgress
      case "CANCELLED": self = .cancelled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Status/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .success
      case 2: self = .failed
      case 3: self = .partialSuccess
      case 4: self = .notStarted
      case 5: self = .inProgress
      case 6: self = .cancelInProgress
      case 7: self = .cancelled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATUS_UNSPECIFIED")
      case .success: return try container.encode("SUCCESS")
      case .failed: return try container.encode("FAILED")
      case .partialSuccess: return try container.encode("PARTIAL_SUCCESS")
      case .notStarted: return try container.encode("NOT_STARTED")
      case .inProgress: return try container.encode("IN_PROGRESS")
      case .cancelInProgress: return try container.encode("CANCEL_IN_PROGRESS")
      case .cancelled: return try container.encode("CANCELLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Stage in the upgrade.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Stage: Codable, Equatable, Sendable {
    /// Unspecified stage.
    case unspecified
    /// Pre-upgrade custom checks, not covered by pg_upgrade.
    case alloydbPrecheck
    /// Pre-upgrade pg_upgrade checks.
    case pgUpgradeCheck
    /// Upgrade the primary instance(downtime).
    case primaryInstanceUpgrade
    /// This stage is read pool upgrade.
    case readPoolInstancesUpgrade
    /// Clone the original cluster.
    case prepareForUpgrade
    /// Rollback in case of critical failures.
    case rollback
    /// Cleanup.
    case cleanup
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .alloydbPrecheck: return 1
      case .pgUpgradeCheck: return 2
      case .primaryInstanceUpgrade: return 3
      case .readPoolInstancesUpgrade: return 4
      case .prepareForUpgrade: return 5
      case .rollback: return 6
      case .cleanup: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STAGE_UNSPECIFIED"
      case .alloydbPrecheck: return "ALLOYDB_PRECHECK"
      case .pgUpgradeCheck: return "PG_UPGRADE_CHECK"
      case .primaryInstanceUpgrade: return "PRIMARY_INSTANCE_UPGRADE"
      case .readPoolInstancesUpgrade: return "READ_POOL_INSTANCES_UPGRADE"
      case .prepareForUpgrade: return "PREPARE_FOR_UPGRADE"
      case .rollback: return "ROLLBACK"
      case .cleanup: return "CLEANUP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Stage/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STAGE_UNSPECIFIED": self = .unspecified
      case "ALLOYDB_PRECHECK": self = .alloydbPrecheck
      case "PG_UPGRADE_CHECK": self = .pgUpgradeCheck
      case "PREPARE_FOR_UPGRADE": self = .prepareForUpgrade
      case "PRIMARY_INSTANCE_UPGRADE": self = .primaryInstanceUpgrade
      case "READ_POOL_INSTANCES_UPGRADE": self = .readPoolInstancesUpgrade
      case "ROLLBACK": self = .rollback
      case "CLEANUP": self = .cleanup
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Stage/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .alloydbPrecheck
      case 2: self = .pgUpgradeCheck
      case 3: self = .primaryInstanceUpgrade
      case 4: self = .readPoolInstancesUpgrade
      case 5: self = .prepareForUpgrade
      case 6: self = .rollback
      case 7: self = .cleanup
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STAGE_UNSPECIFIED")
      case .alloydbPrecheck: return try container.encode("ALLOYDB_PRECHECK")
      case .pgUpgradeCheck: return try container.encode("PG_UPGRADE_CHECK")
      case .primaryInstanceUpgrade: return try container.encode("PRIMARY_INSTANCE_UPGRADE")
      case .readPoolInstancesUpgrade: return try container.encode("READ_POOL_INSTANCES_UPGRADE")
      case .prepareForUpgrade: return try container.encode("PREPARE_FOR_UPGRADE")
      case .rollback: return try container.encode("ROLLBACK")
      case .cleanup: return try container.encode("CLEANUP")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.alloydb.v1.UpgradeClusterResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
